import type { Tour } from '../types.js';

/** Tour catalog in English — mirror of pt-BR.js (same ids and structure). */
export const TOURS_EN: Tour[] = [
  {
    id: 'team-leader',
    icon: 'Users',
    title: 'Team with a leader (zero-config)',
    tagline: 'A leader that assembles and commands the team for you.',
    steps: [
      {
        id: 'leader',
        title: 'Create the team leader',
        body: 'Everything starts with a leader agent (Maestro Mode). It proposes the team, recruits, connects and distributes work on its own. I\'ll create it for you with one click.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'brief',
        title: 'The briefing note',
        body: 'The project spec lives in a note connected to the team. I\'ll create a sample "Briefing" note — edit it with what you want to build.',
        action: { kind: 'createNote', title: 'Briefing', content: '# Briefing\n\nDescribe the project here: goal, scope and definition of done.\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Briefing' },
      },
      {
        id: 'brief-connect',
        title: 'Connect the note to the leader',
        body: 'Connecting the note gives the leader the project context. I\'ll make the connection for you.',
        action: { kind: 'connect', fromTitle: 'Briefing', toTitle: 'Líder' },
        check: { kind: 'edgeExists', fromTitle: 'Briefing', toTitle: 'Líder' },
      },
      {
        id: 'board',
        title: 'The task board',
        body: 'The team kanban: cards in To do/Doing/Done. I\'ll create the board and the first task assigned to the leader — it breaks down and distributes the rest.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'first-task',
        title: 'First task for the leader',
        body: 'I\'ll create the task "Assemble the team and start" assigned to the leader. The complete brief lands in their terminal; every work item they delegate must also exist with an assignee on the board.',
        action: { kind: 'createTask', title: 'Assemble the team and start (read the Briefing note)', assigneeTitle: 'Líder' },
        check: { kind: 'taskExists', titleIncludes: 'Assemble the team' },
      },
      {
        id: 'talk',
        title: 'Give the order',
        body: 'In the leader\'s terminal, say: "read the Briefing note, propose the team and start". Agent consultations count only after ask confirms the reply; when someone finishes with task done, the leader receives the handoff automatically.',
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
    ],
  },
  {
    id: 'vigia-24-7',
    icon: 'Repeat',
    title: '24/7 worker (task watcher)',
    tagline: 'An agent that works nonstop, minute after minute.',
    steps: [
      {
        id: 'leader',
        title: 'The watcher',
        body: 'A leader agent stays on duty: every few minutes it checks the board, assigns whatever has no owner and recruits when people are missing.',
        action: { kind: 'createAgent', title: 'Vigia', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Vigia' },
      },
      {
        id: 'board',
        title: 'The watched board',
        body: 'It needs a board to watch. I\'ll create the Tasks node for you.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'The duty routine',
        body: 'I\'ll create the routine: every 5 minutes the watcher gets "check the board (orkestrai task list); assign what has no owner; recruit if someone is missing".',
        action: { kind: 'createRoutine', targetTitle: 'Vigia', prompt: 'Check the board with: orkestrai task list. Assign whatever has no owner. If an agent is missing, recruit (orkestrai recruit).', intervalMinutes: 5 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'drop-task',
        title: 'Test with a task',
        body: 'Create any task on the board (or use "Do it for me") and watch: within 5 minutes the watcher picks it up and distributes it on its own.',
        action: { kind: 'createTask', title: 'Watcher test task' },
        check: { kind: 'taskExists', titleIncludes: 'Watcher' },
      },
    ],
  },
  {
    id: 'duas-features',
    icon: 'GitBranch',
    title: 'Two features in parallel, no conflicts',
    tagline: 'Two teams, two floors, zero stepping on toes.',
    steps: [
      {
        id: 'floor',
        title: 'Create a floor',
        body: 'A floor is an isolated copy of the project (git worktree) with its own branch. Team B works in it while team A stays on the main one. I\'ll create the "new-feature" floor for you.',
        action: { kind: 'createFloor', name: 'new-feature' },
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
      {
        id: 'agents',
        title: 'One agent per front',
        body: 'I\'ll create two agents: one works on the main floor, the other on the new feature. Move the second to the floor layer (Floors panel in the bottom bar).',
        action: { kind: 'createAgent', title: 'Dev Principal', provider: 'claude' },
      },
      {
        id: 'agent-b',
        title: 'The feature agent',
        body: 'I\'ll create the B-front agent. In the Floors panel, switch the visible layer and drag it there — it starts working in the floor checkout.',
        action: { kind: 'createAgent', title: 'Dev Feature', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Dev Feature' },
      },
      {
        id: 'land',
        title: 'Merging back',
        body: 'When the feature is done: Floors panel → preview shows conflicts BEFORE the merge; land merges everything. Conflicts become a task for an agent to solve. Finish when the floor exists.',
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
    ],
  },
  {
    id: 'qa-visual',
    icon: 'Workflow',
    title: 'Visual QA of your app',
    tagline: 'An agent that opens your app and tests it for real.',
    steps: [
      {
        id: 'portal',
        title: 'The portal (the agents\' browser)',
        body: 'The portal is an embedded browser the agents control. Its persistent name appears in the header and can be edited with the pencil; the URL stays in the separate navigation bar, so both you and agents can target the right Portal by name. I\'ll create one pointing at your dev server — adjust the URL later if it isn\'t localhost:5173. Login pop-ups stay in a sandboxed Orkestrai window with the same persistent session, and the node restores its last navigated page after restart.',
        action: { kind: 'createPortal', url: 'http://localhost:5173', title: 'Portal App' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'responsive-check',
        title: 'Check responsiveness yourself, too',
        body: 'The phone icon in the portal header opens a device toolbar, like a browser\'s: pick iPhone, Pixel, iPad, laptop, or desktop, or type an exact width/height. The page\'s real viewport changes to that size, same as resizing a window, so its own responsive CSS reacts for real.',
      },
      {
        id: 'qa',
        title: 'The QA agent',
        body: 'I\'ll create the agent that will test. Connect it to the portal so it can see the page.',
        action: { kind: 'createAgent', title: 'QA', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'QA' },
      },
      {
        id: 'connect',
        title: 'Connect QA to the portal',
        body: 'Connected, QA navigates, reads the DOM, runs JS and takes screenshots. I\'ll make the connection.',
        action: { kind: 'connect', fromTitle: 'QA', toTitle: 'Portal App' },
        check: { kind: 'edgeExists', fromTitle: 'QA', toTitle: 'Portal App' },
      },
      {
        id: 'test',
        title: 'Ask for the test',
        body: 'In QA\'s terminal: "open the portal, run the app\'s main flow, take a screenshot and tell me what broke". It executes and reports.',
      },
    ],
  },
  {
    id: 'pesquisa-resumo',
    icon: 'Search',
    title: 'Automated research with summary',
    tagline: 'The agent researches the web and writes the summary in a note.',
    steps: [
      {
        id: 'note',
        title: 'The summary note',
        body: 'I\'ll create the "Summary" note — where the agent writes the findings in bullet points.',
        action: { kind: 'createNote', title: 'Summary', content: '# Summary\n\n(research findings appear here in bullet points)\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Summary' },
      },
      {
        id: 'portal',
        title: 'The research portal',
        body: 'I\'ll create a portal open on Google — the agent uses it to read sources.',
        action: { kind: 'createPortal', url: 'https://www.google.com', title: 'Research Portal' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'agent',
        title: 'The researcher',
        body: 'I\'ll create the researcher agent and connect it to the portal and the note — portal to read, note to write.',
        action: { kind: 'createAgent', title: 'Researcher', provider: 'kimi' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Researcher' },
      },
      {
        id: 'connect',
        title: 'Working connections',
        body: 'I\'ll make both connections: Researcher ↔ Research Portal and Researcher ↔ Summary. Then say: "use the portal to read about X and write the summary in the note".',
        action: [
          { kind: 'connect', fromTitle: 'Researcher', toTitle: 'Research Portal' },
          { kind: 'connect', fromTitle: 'Researcher', toTitle: 'Summary' },
        ],
        check: { kind: 'edgeExists', fromTitle: 'Researcher', toTitle: 'Research Portal' },
      },
    ],
  },
  {
    id: 'inbox-arquivos',
    icon: 'FolderPlus',
    title: 'Self-processing file inbox',
    tagline: 'Drop files in the folder; the team processes them in batch.',
    steps: [
      {
        id: 'agent',
        title: 'The processor',
        body: 'I\'ll create the agent that will watch the ./inbox folder in your project (create the folder later if it doesn\'t exist).',
        action: { kind: 'createAgent', title: 'Processor', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Processor' },
      },
      {
        id: 'routine',
        title: 'The sweep routine',
        body: 'I\'ll create the routine: every 2 minutes it lists ./inbox, describes/classifies what\'s new, moves it to ./inbox/done and logs it on the board.',
        action: { kind: 'createRoutine', targetTitle: 'Processor', prompt: 'List ./inbox; for each new file, describe and classify it; move it to ./inbox/done and log it on the board with orkestrai task add.', intervalMinutes: 2 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Drop a file',
        body: 'Create the ./inbox folder in the project and drop any file. Within 2 minutes the processor describes, classifies and archives it.',
      },
    ],
  },
  {
    id: 'revisao-cruzada',
    icon: 'Cable',
    title: 'Cross-review between providers',
    tagline: 'Claude implements, Codex reviews. Two looks per change.',
    steps: [
      {
        id: 'dev',
        title: 'The implementer',
        body: 'I\'ll create the Claude that implements the changes.',
        action: { kind: 'createAgent', title: 'Claude Dev', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Claude Dev' },
      },
      {
        id: 'reviewer',
        title: 'The reviewer',
        body: 'I\'ll create the Codex reviewer — a different model reviewing with another perspective.',
        action: { kind: 'createAgent', title: 'Codex Reviewer', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Codex Reviewer' },
      },
      {
        id: 'connect',
        title: 'Connect the two',
        body: 'I\'ll make the connection: anything one asks the other travels through it (and it glows green while they talk).',
        action: { kind: 'connect', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
        check: { kind: 'edgeExists', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
      },
      {
        id: 'flow',
        title: 'The review flow',
        body: 'Tell Claude Dev: "implement X and ask Codex Reviewer for a review (orkestrai ask)". It implements, Codex critiques, the verdict comes back on the same rope.',
      },
    ],
  },
  {
    id: 'sentinela-deploy',
    icon: 'Rocket',
    title: 'Deploy & tests sentinel',
    tagline: 'Every hour: tests run, failures become a task + notification.',
    steps: [
      {
        id: 'agent',
        title: 'The sentinel',
        body: 'I\'ll create the agent that watches the project\'s health.',
        action: { kind: 'createAgent', title: 'Sentinel', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Sentinel' },
      },
      {
        id: 'board',
        title: 'The incident board',
        body: 'Failures become cards on the board. I\'ll create the Tasks node.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'The hourly patrol',
        body: 'I\'ll create the routine: every 60 minutes it runs the tests; on failure, it opens a task for the team and notifies you on the desktop.',
        action: { kind: 'createRoutine', targetTitle: 'Sentinel', prompt: 'Run the project tests. On failure, open a task for the team (orkestrai task add) and notify the user (orkestrai notify).', intervalMinutes: 60 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Break it on purpose (optional)',
        body: 'Introduce an error in the code and watch the next patrol open the task and fire the native notification.',
      },
    ],
  },
  {
    id: 'preset-bootstrap',
    icon: 'Layers',
    title: 'Your framework preset',
    tagline: 'Build the team once; every new project starts ready.',
    steps: [
      {
        id: 'team',
        title: 'Build the default team',
        body: 'Create the team you use in every project (leader, devs, roles, bootstrap note with your framework conventions). I\'ll create the leader to start.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'save',
        title: 'Save as preset',
        body: 'With the team assembled: pencil next to the workspace name in the sidebar → "Save as preset". The snapshot stores agents, layout, notes, roles and routines (no sessions).',
      },
      {
        id: 'use',
        title: 'Use it in the next project',
        body: 'When creating a new workspace (+ in the sidebar), pick the preset under "Start from a preset" — the whole team is instantiated in the project. Manage presets in Settings.',
      },
    ],
  },
  {
    id: 'portable-role-library',
    icon: 'Layers',
    title: 'Reuse a role from another project',
    tagline: 'Bring proven specialist instructions into this workspace safely.',
    steps: [
      {
        id: 'open-roles',
        title: 'Open Roles',
        body: 'Open Roles from the Canvas toolbar and switch to the Workspace tab to see the roles already installed here.',
      },
      {
        id: 'choose-folder',
        title: 'Choose the source project',
        body: 'Select "Discover from another folder..." and choose the project whose .orkestrai/roles directory contains the specialist instructions.',
      },
      {
        id: 'review-import',
        title: 'Review the imported roles',
        body: 'Only valid new roles are added. Existing names stay untouched; open an imported role before assigning it to an agent.',
      },
    ],
  },
  {
    id: 'pipeline-aprovacao',
    icon: 'Workflow',
    title: 'Write → review → approve pipeline',
    tagline: 'A 3-step flow with a pause for your OK.',
    steps: [
      {
        id: 'agents',
        title: 'Dev and reviewer',
        body: 'I\'ll create the two pipeline agents: the Dev (writes) and the Reviewer (critiques).',
        action: { kind: 'createAgent', title: 'Dev', provider: 'claude' },
      },
      {
        id: 'reviewer',
        title: 'The reviewer',
        body: 'I\'ll create the pipeline reviewer.',
        action: { kind: 'createAgent', title: 'Reviewer', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Reviewer' },
      },
      {
        id: 'flow',
        title: 'The 3-step flow',
        body: 'I\'ll create the Flow node: step 1 the Dev writes ({{input}} = your entry), step 2 the Reviewer critiques the Dev\'s output, step 3 pauses for YOUR approval.',
        action: {
          kind: 'createFlow',
          title: 'Review pipeline',
          steps: [
            { kind: 'agent', target: 'Dev', prompt: 'Write the solution for: {{input}}' },
            { kind: 'agent', target: 'Reviewer', prompt: 'Review critically, point out problems and improvements: {{input}}' },
            { kind: 'approval' },
          ],
        },
        check: { kind: 'nodeExists', nodeType: 'flow' },
      },
      {
        id: 'run',
        title: 'Run the flow',
        body: 'In the Flow node: write the input (e.g., "form validation with zod") and click Run. Watch the steps light up and approve at the final step.',
      },
    ],
  },
  {
    id: 'mcp-tools',
    icon: 'Cable',
    title: 'External tools via MCP',
    tagline: 'GitHub, docs and web in the agents\' hands — with one click.',
    steps: [
      {
        id: 'install',
        title: 'Install an MCP with 1 click',
        body: 'I\'ll install DeepWiki (documentation for any repository, zero configuration) in this workspace — no command, no token.',
        action: { kind: 'installMcp', key: 'deepwiki' },
        check: { kind: 'mcpInstalled', name: 'deepwiki' },
      },
      {
        id: 'market',
        title: 'The MCP marketplace',
        body: 'Skills page → MCPs tab: official curation (GitHub, Gmail, Figma, Drive, Vercel...) + the full registry. Ones that need a token open a guided dialog.',
      },
      {
        id: 'use',
        title: 'Use it in an agent',
        body: 'In an agent terminal (Claude/Kimi), ask something the MCP does — e.g., "ask DeepWiki how auth works in repository X". The tool appears natively in the agent.',
      },
    ],
  },
  {
    id: 'chained-flows',
    icon: 'Workflow',
    title: 'Chained flows',
    tagline: 'One flow triggers the next — compound pipelines and fan-out.',
    steps: [
      {
        id: 'first-flow',
        title: 'The first link',
        body: 'I create the "Research" Flow with an approval step — so you can simulate the stage without needing a real agent.',
        action: { kind: 'createFlow', title: 'Research', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Research' },
      },
      {
        id: 'second-flow',
        title: 'The second link',
        body: 'I create the "Writing" Flow — when Research finishes successfully, its output becomes the Writing input by itself.',
        action: { kind: 'createFlow', title: 'Writing', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Writing' },
      },
      {
        id: 'chain',
        title: 'Connect the two flows',
        body: 'I wire Research → Writing with an edge: the edge is what tells where the output goes when the flow finishes.',
        action: { kind: 'connect', fromTitle: 'Research', toTitle: 'Writing' },
        check: { kind: 'edgeExists', fromTitle: 'Research', toTitle: 'Writing' },
      },
      {
        id: 'run-chain',
        title: 'Run it and watch the chaining',
        body: 'On the Research Flow: click Run and then Approve. When it finishes, Writing fires by itself with the output — failure does not chain and cycles are blocked. Fan-out: connect a third flow to Research and both fire together. And the Sync button turns every agent connected to a flow into a step, in edge order.',
      },
    ],
  },

  {
    id: 'ui-exploration',
    icon: 'PanelsTopLeft',
    title: 'Explore three complete UI directions',
    tagline: 'Compare editable design, tokens, components, prototype, and code before choosing.',
    steps: [
      {
        id: 'open-exploration',
        title: 'Define the outcome once',
        body: 'Use Do it for me to create a complete guided exploration with a brief, tasks, and three editable directions. From the Design menu, you can also describe the objective, audience, platform, stack, constraints, references, and visual modes before creating it.',
        action: { kind: 'createDesignExploration', title: 'Guided UI exploration', objective: 'Explore three complete visual directions for an interface that is clear, distinctive, and ready for implementation.', audience: 'People who will use the product on desktop and mobile.' },
        check: { kind: 'nodeExists', nodeType: 'group' },
      },
      {
        id: 'inspect-package',
        title: 'Start small and track progress',
        body: 'Orkestrai creates one linked spec, eight progressive tasks, and three native Design documents. Each designer first delivers only one desktop screen and one mobile screen. The node status identifies who is waiting, working, stalled for five minutes, or ready for review.',
        check: { kind: 'nodeExists', nodeType: 'design' },
      },
      {
        id: 'compare-directions',
        title: 'Review the visual concept',
        body: 'Open Quality inside each document and use Visual review to approve it or request changes with traceable feedback. Evaluate hierarchy, composition, identity, clarity, and polish: the automatic audit checks structure, not taste or visual quality.',
      },
      {
        id: 'approve-deliver',
        title: 'Expand only what was approved',
        body: 'After approval, the chosen direction receives responsive states, tokens, components, a prototype, and code. Validate it in a Portal or mobile device, run tests, and register the Git-linked result in Review Center.',
      },
    ],
  },
  {
    id: 'design-figma',
    icon: 'Palette',
    title: 'Design together with your AI team',
    tagline: 'One native visual document for you, the designer, and the leader.',
    steps: [
      {
        id: 'document',
        title: 'Create a native design document',
        body: 'I create an Interface Design node on the same Canvas as the team. Its structured document stays inside .orkestrai/designs in your workspace.',
        action: { kind: 'createDesign', title: 'Interface Design' },
        check: { kind: 'nodeExists', nodeType: 'design', titleIncludes: 'Interface Design' },
      },
      {
        id: 'open',
        title: 'Open Design Mode',
        body: 'Open the same document in full Canvas Design Mode. Tooltips show every tool and shortcut. Pen previews the next segment and close target; click or drag to draw, then press Enter or double-click the path to edit it. Bend or split segments, continue an endpoint, and choose Corner, Mirrored, Asymmetric, or Disconnected tangents.',
        action: { kind: 'openDesign', title: 'Interface Design' },
      },
      {
        id: 'compose',
        title: 'Compose responsive vector interfaces',
        body: 'Box-select vector points and transform them together, resize any layer from eight handles, and edit multiline text directly on the canvas. Shift-select layers to align, distribute, combine, mask, or group them; move and resize group descendants together, Alt-select a nested layer, and find, select, or replace matching fill and stroke colors across the page.',
      },
      {
        id: 'assets-export',
        title: 'Bring assets in and approved work out',
        body: 'Paste, drop, or choose an SVG to turn its paths, shapes, transforms, styles, and gradients into editable native layers. Raster images stay in the reusable asset library. Copy a selection as SVG or PNG, or export the selection or full page as SVG, PNG, JPEG, WebP, or PDF.',
      },
      {
        id: 'design-system',
        title: 'Make the visual language reusable',
        body: 'Open Variables beside Layers. Start from a product, marketing, or mobile preset, import DTCG/CSS or export DTCG/CSS/Tailwind; create modes, aliases, and bindings, then audit repetition. Under Components, turn frames into reusable sources and create instances, properties, variants, and slots. Under Libraries, share versions only with authorized workspaces. Under Code, extract CSS variables, Tailwind, and Svelte, React, or Vue contracts without executing files and connect the visual source to its implementation. Agents use the same revision-safe command bus.',
      },
      {
        id: 'figma-bridge',
        title: 'Link the same work to Figma',
        body: 'Open Components → Figma. The official MCP is already managed for compatible agents. Store a read-only REST token in the operating-system vault, paste a Figma page or frame link, inspect it, select what enters the native document, and review remote, local, or conflicting changes before synchronization. Keeping the local version queues only that reviewed layer for Figma. Install the first-party plugin from its folder, paste the workspace-scoped loopback connection copied by Orkestrai, then transfer a live selection or send only the queued layers back.',
      },
      {
        id: 'designer',
        title: 'Add a designer to the same document',
        body: 'I create a Designer agent. It can inspect and edit the exact structured document with typed Orkestrai tools instead of guessing from a screenshot.',
        action: { kind: 'createAgent', title: 'Designer', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Designer' },
      },
      {
        id: 'connect',
        title: 'Make the collaboration visible',
        body: 'I connect the Design node to the Designer. The agent reads the current revision, applies a typed operation, and verifies the result while your editor updates live.',
        action: { kind: 'connect', fromTitle: 'Interface Design', toTitle: 'Designer' },
        check: { kind: 'edgeExists', fromTitle: 'Interface Design', toTitle: 'Designer' },
      },
    ],
  },
  {
    id: 'design-delivery',
    icon: 'Code2',
    title: 'Deliver a design as working code',
    tagline: 'Import, generate, compare, and review without breaking the visual source.',
    steps: [
      {
        id: 'document',
        title: 'Start from one native document',
        body: 'I create a Design Delivery node. The same structured document remains the source for manual editing, agents, generated code, and visual evidence.',
        action: { kind: 'createDesign', title: 'Design Delivery' },
        check: { kind: 'nodeExists', nodeType: 'design', titleIncludes: 'Design Delivery' },
      },
      {
        id: 'open-code',
        title: 'Open the Code delivery area',
        body: 'Open the Design document, choose Components, then Code. Connect scans tokens and real components; Import code, Generate, and Validate are adjacent workflow steps instead of separate tools.',
        action: { kind: 'openDesign', title: 'Design Delivery' },
      },
      {
        id: 'import',
        title: 'Bring an existing interface into the scene graph',
        body: 'Under Import code, choose HTML/Tailwind, Svelte, React/JSX, or Vue and paste markup plus optional CSS. Review compatibility notes, then create editable native layers. Project scripts and configuration are never executed.',
      },
      {
        id: 'generate',
        title: 'Preview before writing implementation code',
        body: 'Select a frame or group, choose Svelar/Svelte 5, React, Next.js, Vue 3, or HTML/Tailwind, and set the workspace path. Preview the full file first. Compatible Code Connect mappings reuse real components; writing is blocked if the file changed after preview, and the result opens directly in Monaco. Agents use the same revision-safe flow through typed Orkestrai MCP tools or the bundled CLI.',
      },
      {
        id: 'validate',
        title: 'Compare with a live implementation',
        body: 'Keep a Portal visible or attach an iOS/Android device, choose a frame or responsive viewport, and capture. Inspect the normalized design, implementation, adjustable overlay, and pixel diff rather than relying on memory.',
      },
      {
        id: 'trace',
        title: 'Keep feedback tied to the work',
        body: 'Create a Kanban feedback task with reference, implementation, and diff screenshots, or create a Review Center entry tied to the generated Git file. The leader can assign it and the reviewer can approve the actual change.',
      },
    ],
  },
  {
    id: 'design-prototype',
    icon: 'PlaySquare',
    title: 'Build an interactive prototype',
    tagline: 'Connect screens, animate layers, and share one testable experience.',
    steps: [
      {
        id: 'document',
        title: 'Start from the native design source',
        body: 'I create a Product Prototype Design node. Its frames, variables, components, interactions, and motion all share one revision history.',
        action: { kind: 'createDesign', title: 'Product Prototype' },
        check: { kind: 'nodeExists', nodeType: 'design', titleIncludes: 'Product Prototype' },
      },
      {
        id: 'open',
        title: 'Open the Prototype inspector',
        body: 'Open the document and select Prototype in the right inspector. Create a starting flow, then select a frame or layer to expose its interaction and scrolling controls.',
        action: { kind: 'openDesign', title: 'Product Prototype' },
      },
      {
        id: 'interactions',
        title: 'Connect behavior to the selected layer',
        body: 'Add click, press, hover, or timed triggers for frame navigation, overlays, back, scrolling, or variable modes. Play the flow to verify transitions, fixed layers, hotspots, and overflow in context.',
      },
      {
        id: 'motion',
        title: 'Animate with reusable tokens and keyframes',
        body: 'Switch to Motion, create a duration and easing token, add a track to a selected layer, then edit its timeline and keyframes. Copy CSS keyframes or Motion.dev output when implementation needs the same behavior.',
      },
      {
        id: 'share',
        title: 'Present or share without exposing the workspace',
        body: 'Use the focused player for device framing, hotspots, fullscreen, restart, and back. Share exports a self-contained read-only HTML prototype that keeps the approved interaction flow portable.',
      },
    ],
  },
  {
    id: 'managed-ports',
    icon: 'RadioTower',
    title: 'Release dev server ports',
    tagline: 'See and stop local listeners without leaving the canvas.',
    steps: [
      {
        id: 'portal',
        title: 'Register the app in a Portal',
        body: 'I create a local Portal on port 4173. This persisted link is what lets Orkestrai manage the port safely.',
        action: { kind: 'createPortal', url: 'http://localhost:4173', title: 'Dev Portal' },
        check: { kind: 'nodeExists', nodeType: 'portal', titleIncludes: 'Dev Portal' },
      },
      {
        id: 'server',
        title: 'Start your dev server',
        body: 'In the project terminal, start the app on the same port as the Portal. You can use `orkestrai port 4173` to pick a free port before starting the server.',
      },
      {
        id: 'panel',
        title: 'Open Ports and release the listener',
        body: 'In the bottom toolbar, immediately after Usage, open Ports. The process appears as in use; click the stop icon and confirm. The Portal stays saved for the next run.',
      },
    ],
  },
  {
    id: 'leader-dictation',
    icon: 'Mic',
    title: 'Dictate into any field',
    tagline: 'Speak wherever you are writing, without requiring a leader.',
    steps: [
      {
        id: 'field',
        title: 'Place the cursor',
        body: 'Focus any editable field: task title or description, role, note, or form. Dictation follows the last field and its current selection.',
      },
      {
        id: 'record',
        title: 'Click the voice orb',
        body: 'Use the colored orb or Alt+Space to record. The first click preserves the focused field. Its small clickable badge shows whether it is pinned or movable and opens position controls directly; the tooltip also displays the Ctrl-click or Command-click shortcut. Unpin the orb to drag it inside the visible canvas.',
      },
      {
        id: 'auto-submit',
        title: 'Choose whether the terminal sends',
        body: 'Under Settings → Voice dictation, enable Send automatically in terminals to append Enter to the transcript. It only submits in terminals; kanban, roles, notes, and forms still only receive text.',
      },
      {
        id: 'fallback',
        title: 'Use the leader shortcut in either view',
        body: 'With no active field, the orb sends the transcript to the Maestro leader in Canvas or Workbench. I create one to test; without a field or leader, the app shows a warning. On macOS, Fn/Globe by itself is reserved by the system, so configure a key combination or F1–F12.',
        action: { kind: 'createAgent', title: 'Voice Leader', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Voice Leader' },
      },
    ],
  },
  {
    id: 'audio-devices',
    icon: 'Mic',
    title: 'Choose and test audio devices',
    tagline: 'Use the right microphone and speaker everywhere in Orkestrai.',
    steps: [
      {
        id: 'open-settings',
        title: 'Open Voice settings',
        body: 'Open Settings → Voice. Audio devices appear above the voice engine, so input and output routing stay separate from the STT and TTS models.',
      },
      {
        id: 'grant-and-choose',
        title: 'Reveal and choose the microphone',
        body: 'Click Refresh to grant microphone access and reveal device names. Choose an input, click Test microphone, and confirm that the live level meter reacts before saving.',
      },
      {
        id: 'test-output',
        title: 'Test the speaker',
        body: 'Choose an output and play the short test tone. Every preview and spoken reply uses it. If this platform cannot select a specific output, Orkestrai explains that the system default will be used.',
      },
      {
        id: 'recover',
        title: 'Recover without guessing',
        body: 'Dictation captures direct PCM through the same Web Audio route as the live meter and normalizes quiet speech locally. If a selected device is disconnected, Orkestrai returns to the system default. Capture errors distinguish permission, missing hardware, interruption, likely contention, and a microphone that opens without producing signal.',
      },
    ],
  },
  {
    id: 'switch-agent-provider',
    icon: 'Cable',
    title: 'Change an agent provider',
    tagline: 'Change the execution model without dismantling the team.',
    steps: [
      {
        id: 'open',
        title: 'Open the switcher in the header',
        body: 'Click ⇄ on the agent you want to replace. The menu lists providers detected on this device and marks the current one.',
      },
      {
        id: 'choose',
        title: 'Choose an installed provider',
        body: 'The switch closes the previous PTY and conversation, then starts a clean session with the new adapter and its access flags.',
      },
      {
        id: 'preserve',
        title: 'Continue with the same member',
        body: 'Name, role, Maestro Mode, floor, position, and connections remain. Reapply any needed context in the new conversation and continue from the same board.',
      },
    ],
  },
  {
    id: 'multilingual-spoken-replies',
    icon: 'Languages',
    title: 'Spoken replies in three languages',
    tagline: 'Choose, test and use a local voice suited to the language.',
    steps: [
      {
        id: 'choose',
        title: 'Choose the voice in Settings',
        body: 'Open Settings → Voice and select Portuguese (Brazil), English (United States) or Spanish (Latin America). Each option sets both the speaker and synthesis language.',
      },
      {
        id: 'preview',
        title: 'Listen before using it',
        body: 'Adjust speed from 0.75× to 1.50× and click Play preview. On first use, confirm the local download; after that all three voices work offline on macOS, Linux and Windows.',
      },
      {
        id: 'enable',
        title: 'Enable it on the agent',
        body: 'Return to the canvas and click the speaker in the terminal. The next reply is spoken with the selected voice, sentence by sentence, while dictation continues using the same Parakeet as before.',
      },
    ],
  },
  {
    id: 'team-template-library',
    icon: 'LayoutTemplate',
    title: 'Start with a ready-made team',
    tagline: 'Choose the stack and get agents, roles, skills, and a board already organized.',
    steps: [
      {
        id: 'preset-library',
        title: 'Open the preset library',
        body: 'Use the template icon in the sidebar or Presets in the bottom toolbar. Filter by Product, Development, Design and creative, Marketing and content, or Orkestrai.',
      },
      {
        id: 'create-or-merge',
        title: 'Create from scratch or add to the current team',
        body: 'New workspace prepares the selected project with layout, tasks, roles, and skills. The + button adds the same team to the current canvas without removing your nodes.',
      },
      {
        id: 'operate',
        title: 'Complete the team and track floors',
        body: 'Extensive roles enter automatically in the first session and the lead receives the complete initial task to assign. In Floors, track each task title, stage, and actual assignee before reviewing and landing.',
      },
    ],
  },
  {
    id: 'custom-board-stages',
    icon: 'Workflow',
    title: 'Adapt the board to your process',
    tagline: 'Replace a generic kanban with the stages your team actually uses.',
    steps: [
      {
        id: 'board',
        title: 'Create the work board',
        body: 'I create a Tasks node. It starts simple and can represent a campaign, content production, design project, or software delivery.',
        action: { kind: 'createTasksBoard' },
        check: { kind: 'nodeExists', nodeType: 'tasks', titleIncludes: 'Tasks' },
      },
      {
        id: 'stages',
        title: 'Define your stages',
        body: 'Click the columns icon in the board header. Rename, recolor, reorder, and add stages such as Ideas, Approval, and Published.',
      },
      {
        id: 'team-awareness',
        title: 'The team follows the same workflow',
        body: 'The lead and specialists receive the stages automatically. They create and move deliveries while you track everything visually.',
      },
    ],
  },
  {
    id: 'campaign-ready-team',
    icon: 'Palette',
    title: 'Launch a campaign with a ready team',
    tagline: 'Strategy, research, copy, and measurement arrive already organized.',
    steps: [
      {
        id: 'library',
        title: 'Open the Preset library',
        body: 'Choose Marketing and content → Campaign and launch. Brand and design and Content and SEO are ready for other kinds of work.',
      },
      {
        id: 'apply',
        title: 'Start new or add to this workspace',
        body: 'New workspace creates the team in another folder. The + button adds its lead and specialists to the current canvas without removing anything.',
      },
      {
        id: 'brief',
        title: 'Complete the brief and set the objective',
        body: 'Fill in objective, audience, offer, channels, deadline, and measurement in the created note. Then talk to the lead, which coordinates research, copy, distribution, and approval.',
      },
    ],
  },
  {
    id: 'orkestrai-consensus-team',
    icon: 'LayoutTemplate',
    title: 'Contribute to Orkestrai through consensus',
    tagline: 'Claude, Codex, and Kimi agree on the plan before execution.',
    steps: [
      {
        id: 'apply',
        title: 'Apply Orkestrai Contributing',
        body: 'In the Library’s Orkestrai category, create the complete team with a lead, two oracles, and Svelar, desktop, and QA/release specialists.',
      },
      {
        id: 'consensus',
        title: 'Run the consensus Flow',
        body: 'Codex proposes or audits architecture, Kimi reviews product, UX, and risks, and Claude synthesizes. Both oracles must answer APPROVED.',
      },
      {
        id: 'delivery',
        title: 'Only then distribute tasks',
        body: 'After approval, the lead records the decision, creates complete briefs, and tracks Review and Validation until tests, build, documentation, and changelog pass.',
      },
    ],
  },
  {
    id: 'provider-center-setup',
    icon: 'Cable',
    title: 'Prepare your AI providers',
    tagline: 'See what is ready and follow official setup without guessing commands.',
    steps: [
      {
        id: 'open-center',
        title: 'Open Provider Center',
        body: 'Use the cable icon in the left sidebar, Cmd/Ctrl+2, or Workspace → Provider Center. It checks Claude, Codex, Kimi, OpenCode, Cursor, Antigravity, Cline, Devin, and GitHub Copilot locally.',
      },
      {
        id: 'follow-setup',
        title: 'Follow the setup for your device',
        body: 'Expand an agent to see the official guide and, when available, an installation command for macOS, Windows, or Linux. Complete sign-in in the provider’s own CLI; Orkestrai never receives the credential.',
      },
      {
        id: 'verify',
        title: 'Check again and create the agent',
        body: 'Return to Provider Center and use Check again. When the CLI is detected, go back to the canvas and create that agent from the bottom toolbar.',
      },
      {
        id: 'multi-account',
        title: 'Use a second account with Profiles',
        body: 'If the provider has a verified account-directory override, a Profiles section appears when you expand it: create a named profile (e.g. "Work") pointing to that account\'s official config location. Pick it right in the New agent dialog, or later from the terminal menu, and Usage routing can select it too. Credentials stay in provider-owned files and are resolved only when the PTY starts.',
      },
    ],
  },
  {
    id: 'choose-agent-provider',
    icon: 'Users',
    title: 'Choose agents without learning the terminal',
    tagline: 'Use a service you already have and organize the team by outcome.',
    steps: [
      {
        id: 'available',
        title: 'See what is already available',
        body: 'The bottom toolbar detects Claude, Codex, Kimi, OpenCode, Cursor, Antigravity, Cline, Devin, and GitHub Copilot. Available services are active; disabled ones only need installation and sign-in.',
      },
      {
        id: 'outcome',
        title: 'Name the work, not the technology',
        body: 'Create “Audience research”, “Art direction”, “Campaign copy”, or “Product review”. Roles, notes, and tasks tell the agent what to deliver even if you never use a terminal outside Orkestrai.',
      },
      {
        id: 'perspective',
        title: 'Combine only when it helps',
        body: 'One provider is enough to start. Add another to review an important decision or bring an independent perspective; Orkestrai keeps every conversation separate and tied to the workspace.',
      },
    ],
  },
  {
    id: 'pin-favorite-agents',
    icon: 'Pin',
    title: 'Keep favorite agents within reach',
    tagline: 'Make the toolbar fit your routine without hiding other options.',
    steps: [
      {
        id: 'open-agents',
        title: 'Open the Agents menu',
        body: 'Use Agents in the bottom toolbar to see every supported service. Selecting a ready agent arms the same draw tool as before; an agent that needs setup opens Provider Center.',
      },
      {
        id: 'pin-favorites',
        title: 'Pin up to four favorites',
        body: 'In Pinned to toolbar, check the services you use most. Ready favorites appear as direct buttons beside Agents in the order you selected them.',
      },
      {
        id: 'keep-your-preference',
        title: 'Use the same toolbar everywhere',
        body: 'Your selection is global and survives workspace switches and app restarts. If a pinned CLI becomes unavailable, it stays saved but does not take toolbar space.',
      },
    ],
  },
  {
    id: 'devin-local-agent',
    icon: 'Cable',
    title: 'Add Devin to the local team',
    tagline: 'Use the official local agent with the same canvas workflow.',
    steps: [
      {
        id: 'prepare',
        title: 'Prepare the official CLI',
        body: 'Open Provider Center, expand Devin, and follow the installation and sign-in guidance. Check again until Devin appears as ready.',
      },
      {
        id: 'create',
        title: 'Create the Devin member',
        body: 'Return to the canvas and select Devin in the bottom toolbar. Search or scroll the bounded model list, choose one available to your account, and start with autonomous workspace access.',
      },
      {
        id: 'continue',
        title: 'Work through the bridge',
        body: 'Connect Devin to the leader, board, or notes. Orkestrai provisions its MCP tools and skill, keeps agent replies clean, and resumes the exact conversation after a restart.',
      },
    ],
  },
  {
    id: 'quota-aware-delegation',
    icon: 'RadioTower',
    title: 'Quota-aware delegation',
    tagline: 'The leader sees provider limits before distributing new work.',
    steps: [
      {
        id: 'add-usage',
        title: 'Put Usage on the canvas',
        body: 'I create a persistent Usage node with Claude as source, Codex as fallback, and a 90% initial threshold. It checks Claude, Codex, and Kimi every five minutes.',
        action: { kind: 'createUsage', title: 'Provider usage' },
        check: { kind: 'nodeExists', nodeType: 'usage', titleIncludes: 'Provider usage' },
      },
      {
        id: 'understand-provider-capabilities',
        title: 'Read verified capacity only',
        body: 'Claude, Codex, and Kimi report automatic percentages. Antigravity points to /usage or /quota; Cursor and Devin explain their administrative API requirement; OpenCode and Cline point to the selected model provider. Orkestrai never invents a quota.',
      },
      {
        id: 'set-policy',
        title: 'Adjust the policy',
        body: 'Leader routing is the first section in the node. Choose the source, a different fallback, the 5-hour, weekly, or monthly window, and the percentage that means "near the limit". Provider details scroll below without zooming the canvas, including in compact saved nodes. If the provider does not report that period, the node asks for another window.',
      },
      {
        id: 'leader-checks',
        title: 'The leader checks before delegating',
        body: 'The skill teaches the leader to call orkestrai usage before distributing new work. It recommends a healthy fallback without silently moving tasks or conversations already in progress.',
      },
    ],
  },
  {
    id: 'organize-canvas',
    icon: 'LayoutGrid',
    title: 'Organize the canvas',
    tagline: 'Realign a selection or the whole workspace without overlaps.',
    steps: [
      {
        id: 'choose-scope',
        title: 'Choose what moves',
        body: 'Select the nodes that need attention. With a selection, Orkestrai moves only those nodes; with nothing selected, it organizes the entire canvas.',
      },
      {
        id: 'run-layout',
        title: 'Run Organize canvas',
        body: 'Use the toolbar action, command palette, or Command+Shift+T. The deterministic layout arranges nodes into readable rows without stacking them.',
      },
      {
        id: 'keep-connections-clear',
        title: 'Keep the workspace readable',
        body: 'Connections remain behind every node, including on Windows displays with different scale factors. You can still fine-tune positions manually afterward.',
      },
    ],
  },
  {
    id: 'focused-workspace-view',
    icon: 'PanelLeftOpen',
    title: 'Work in the Workbench',
    tagline: 'Open, organize, and compare artifacts without losing the canvas.',
    steps: [
      {
        id: 'switch-view',
        title: 'Switch the view',
        body: 'Use Canvas/Workbench in the upper-left corner or open Workbench from the Workspace menu. Agents remain in the same sessions while you switch modes; terminal font metrics settle before reattachment so the cursor remains aligned after visiting Settings or documentation.',
      },
      {
        id: 'choose-item',
        title: 'Choose where to work',
        body: 'Expand a workspace or use search. Open items use vertical tabs by default; you can choose horizontal tabs under Settings → Appearance.',
      },
      {
        id: 'split-work',
        title: 'Build your work area',
        body: 'Split the active pane right or down and arrange up to eight resizable artifacts. Drag tabs between panes or use the Move to menu; the layout returns with the workspace.',
      },
      {
        id: 'attach-context',
        title: 'Keep references with the work',
        body: 'Drop, paste, or select images, PDFs, files, and links in notes, cards, or the agent composer. Files up to 10 MB stay in the workspace and the complete reference reaches the brief.',
      },
      {
        id: 'monitor-provider-usage',
        title: 'Monitor quotas in the footer',
        body: 'The footer shows the 5-hour, weekly, and monthly windows actually reported by Claude, Codex, and Kimi. Click any provider to open Usage details.',
      },
      {
        id: 'terminal-options',
        title: 'Keep terminal options organized',
        body: 'Open the ellipsis menu in the header to change provider or role, visually choose 1 of 15 ANSI themes, reload, toggle Maestro Mode, or remove the terminal.',
      },
      {
        id: 'dictate-to-leader',
        title: 'Dictate without returning to Canvas',
        body: 'When pinned, the voice orb uses a dedicated header slot without covering tabs or actions. With no text field active, it finds the workspace leader, opens that terminal, and starts the same flow used in Canvas.',
      },
      {
        id: 'return-canvas',
        title: 'Return to visual context',
        body: 'Click the canvas icon in the header or use the switch. The workspace stays active and the selected node is centered on the canvas.',
      },
    ],
  },
  {
    id: 'edit-and-preview-files',
    icon: 'FileCode2',
    title: 'Edit and preview files',
    tagline: 'Use a complete local editor and inspect common file formats in place.',
    steps: [
      {
        id: 'open-file',
        title: 'Open a workspace file',
        body: 'Expand Files in the Workbench sidebar and choose a text file. It opens directly in a local editor tab without adding a node to Canvas. Monaco keeps cursor, selection, undo, and unsaved edits across tabs and panes.',
      },
      {
        id: 'use-editor-tools',
        title: 'Use the editor tools',
        body: 'Find or replace text, navigate symbols, format supported files, and toggle wrapping or the minimap. Settings → Appearance also offers font size and optional autosave.',
      },
      {
        id: 'inspect-previews',
        title: 'Inspect without another app',
        body: 'Switch Markdown between source and preview, browse and zoom PDFs, or pan and zoom images. Binary files show safe metadata and can open in the system application.',
      },
      {
        id: 'protect-edits',
        title: 'Keep changes explicit',
        body: 'Unsaved tabs show a status dot and ask before closing. Files above 512 KB open read-only so content that was not loaded is never overwritten.',
      },
    ],
  },
  {
    id: 'share-reference-material',
    icon: 'Paperclip',
    title: 'Share reference material',
    tagline: 'Keep images, PDFs, files, and links beside the brief agents receive.',
    steps: [
      {
        id: 'prepare-reference-note',
        title: 'Prepare a traceable brief',
        body: 'Create a note to collect the objective, constraints, and work references. It remains a Canvas node and can also open in Workbench.',
        action: { kind: 'createNote', title: 'Brief with references', content: '# Brief\n\n## Objective\n\n## References\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Brief with references' },
      },
      {
        id: 'attach-reference',
        title: 'Attach it in the right context',
        body: 'Drag, paste, or select an image, PDF, file, or HTTP/HTTPS link in the note, an agent composer, or a task. The item appears with its name, type, and an explicit remove action.',
      },
      {
        id: 'deliver-complete-context',
        title: 'Deliver the complete brief',
        body: 'Connect the note to the leader or assign the task. The agent receives the title, description, and references with relative paths under .orkestrai/attachments, without relying on pasted text or conversation memory.',
      },
    ],
  },
  {
    id: 'universal-workspace-search',
    icon: 'Search',
    title: 'Use universal search',
    tagline: 'Find and open any part of the work with Command/Ctrl+K.',
    steps: [
      {
        id: 'open-search',
        title: 'Open it from any screen',
        body: 'Press Command/Ctrl+K to search workspaces, agents, tasks, notes, roles, skills, files, settings, and commands.',
      },
      {
        id: 'inspect-result',
        title: 'Check the context',
        body: 'Navigate the groups and read the preview before opening. Star frequent items; recently used items return the next time search opens.',
      },
      {
        id: 'place-result',
        title: 'Choose where it opens',
        body: 'Open in the current pane, right, or below. Prefix the term with content: to search inside files, always confined to the workspace folder.',
      },
    ],
  },
  {
    id: 'monitor-team-control-center',
    icon: 'Activity',
    title: 'Monitor the team in Control Center',
    tagline: 'See real activity and verify every handoff without waking idle agents.',
    steps: [
      {
        id: 'open-control-center',
        title: 'Open the operational view',
        body: 'Go to Workbench, expand a workspace, and open Control Center above Files. It is a local Workbench view and does not create another Canvas node.',
        action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-control-center:{workspace}' },
      },
      {
        id: 'read-agent-state',
        title: 'Read the real agent state',
        body: 'Compare working, waiting for input or permission, blocked, idle, done, error, and disconnected agents. Activity turns messages, tasks, reviews, decisions, Git work, and system events into a readable timeline.',
      },
      {
        id: 'verify-delivery',
        title: 'Verify communications',
        body: 'The inbox projects queued, sent, delivered, acknowledged, replied, and failed transitions into one canonical message envelope. Replays are idempotent and a successful orkestrai ask always ends with a confirmed reply.',
      },
      {
        id: 'switch-without-waking',
        title: 'Move between workspaces safely',
        body: 'Switch views or restart the app. Event history reconstructs the Control Center without injecting prompts or activating idle terminals; native notifications remain reserved for real attention and completion.',
      },
    ],
  },
  {
    id: 'triage-attention-center',
    icon: 'BellRing',
    title: 'Triage attention across every workspace',
    tagline: 'Handle real questions and blockers without scanning every terminal.',
    steps: [
      {
        id: 'open-attention-center',
        title: 'Open the global inbox',
        body: 'Use the bell beside the Canvas/Workbench switch. It stays available in both views and does not wake any agent.',
        action: { kind: 'openPage', path: '/canvas?workspace={workspace}' },
      },
      {
        id: 'prioritize-signals',
        title: 'Start with the current workspace',
        body: 'Questions, permission requests, blockers, and failures are gathered from every workspace, with the current workspace and highest severity first.',
      },
      {
        id: 'defer-or-resolve',
        title: 'Open, snooze, or resolve',
        body: 'Open the exact source, mark it read, snooze it for one hour, or resolve it. Every action keeps the persisted audit trail.',
      },
      {
        id: 'search-history',
        title: 'Recover the history later',
        body: 'Use Command/Ctrl+K with type:attention, workspace:"Name", agent:"Name", status:open, has:error, before:, or after: to find the same signal again.',
      },
    ],
  },
  {
    id: 'trace-delivery-workstream',
    icon: 'Route',
    title: 'Trace a complete delivery in Workstreams',
    tagline: 'Keep the task, team, decisions, review, and Git evidence in one flow.',
    steps: [
      {
        id: 'open-workstreams',
        title: 'Open the delivery view',
        body: 'Expand the workspace in Workbench and open Workstreams, or find it through Command/Ctrl+K. The view projects existing records and does not create another Canvas node.',
        action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-workstreams:{workspace}' },
      },
      {
        id: 'start-from-task',
        title: 'Use the Kanban task as the identity',
        body: 'Create and assign the real task on the board. Its column, assignee, active Floor, branch, and semantic activity appear automatically in the workstream.',
      },
      {
        id: 'connect-decisions-and-review',
        title: 'Keep decisions and review attached',
        body: 'Ask Council perspectives from the workstream so they receive the same brief. Create the Review Center record against that task and select the exact revision, files, evidence, tests, and risks.',
      },
      {
        id: 'inspect-delivery-trace',
        title: 'Read the complete trace',
        body: 'Compare the activity timeline, Council progress, review status, and linked Git paths. Unlinked records stay explicitly counted instead of being attributed to the wrong delivery.',
      },
    ],
  },
  {
    id: 'preserve-sourced-workspace-memory',
    icon: 'BookMarked',
    title: 'Preserve sourced workspace memory',
    tagline: 'Keep durable knowledge useful without turning every conversation into a fact.',
    steps: [
      { id: 'open-workspace-memory', title: 'Open the shared memory', body: 'Open Workspace memory from the Workbench explorer, Canvas command palette, or Command/Ctrl+K.', action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-memory:{workspace}' } },
      { id: 'record-durable-knowledge', title: 'Record only reusable knowledge', body: 'Choose decision, fact, preference, constraint, reference, or lesson. Add concise content, confidence, tags, and pin only what deserves priority.' },
      { id: 'attach-memory-source', title: 'Attach the evidence', body: 'Add at least one user statement, note, task, message, file, URL, Git reference, review, Council, or agent source. Labels and excerpts make provenance understandable.' },
      { id: 'revise-memory-safely', title: 'Revise without erasing history', body: 'Use Revise when knowledge changes. The previous revision remains auditable and a stale editor cannot silently overwrite a newer value.' },
    ],
  },
  {
    id: 'triage-traceable-annotations',
    icon: 'MessageSquareText',
    title: 'Triage traceable annotations',
    tagline: 'Keep code and design feedback attached to the artifact that created it.',
    steps: [
      { id: 'open-annotation-center', title: 'Open the unified view', body: 'Open Annotation Center from Canvas, the Workbench explorer, or Command/Ctrl+K.', action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-annotations:{workspace}' } },
      { id: 'filter-annotation-center', title: 'Find the feedback that matters', body: 'Switch between open, resolved, and all items. Search by comment, author, review, file, Design document, or layer.' },
      { id: 'inspect-annotation-source', title: 'Check revision and context', body: 'Inspect the captured revision and stale warning. Code comments detect later file changes; Design threads retain their document revision and layer target.' },
      { id: 'resolve-at-source', title: 'Return to the canonical artifact', body: 'Choose Open source to reply or resolve in Review Center or the native Design document. Annotation Center never forks the feedback state.' },
    ],
  },
  {
    id: 'version-and-share-team-pack',
    icon: 'PackageOpen',
    title: 'Version and share a Team Pack',
    tagline: 'Reuse a complete team without carrying sessions or secrets.',
    steps: [
      { id: 'open-team-packs', title: 'Open Team Packs', body: 'Open the preset library from the Canvas. Built-in and existing presets continue to work, while custom workspace snapshots support version history.', action: { kind: 'openPage', path: '/canvas?workspace={workspace}' } },
      { id: 'capture-team-pack', title: 'Capture the working team', body: 'Save the workspace as a custom pack. Agents, roles, skills, stages, task templates, routines, MCP configuration, connections, and layout are included; live runtime state is removed.' },
      { id: 'publish-team-pack', title: 'Publish an immutable revision', body: 'Open version history, enter a larger semantic version and release notes, and publish. The previous checksummed revision remains unchanged.' },
      { id: 'share-team-pack', title: 'Export or import safely', body: 'Export the checksum-protected JSON or import one from another installation. Orkestrai validates format, size, content limits, and SHA-256 before creating a new local pack.' },
    ],
  },
  {
    id: 'run-agent-huddle',
    icon: 'MessageCircleMore',
    title: 'Run a persistent agent huddle',
    tagline: 'Bring the right agents into one voice-assisted, traceable conversation.',
    steps: [
      { id: 'open-huddles', title: 'Open Huddles', body: 'Open Huddles from the Canvas toolbar, Workbench explorer, native Workspace menu, or Command/Ctrl+K.', action: { kind: 'openPage', path: '/canvas?workspace={workspace}' } },
      { id: 'choose-huddle-room', title: 'Set the room', body: 'Enter a topic and optional agenda, choose up to eleven agents, and identify the facilitator. Only one active huddle is allowed in a workspace.' },
      { id: 'hold-huddle-turn', title: 'Address the right participants', body: 'Select up to five participating agents, then type or dictate your turn. Pending, completed, failed, and contributed replies stay ordered in the persisted transcript; optional TTS reads only new agent replies.' },
      { id: 'close-huddle-loop', title: 'Turn the decision into work', body: 'End the huddle explicitly and create a linked Kanban task when follow-up is required. The agenda and bounded transcript become traceable evidence in the related Workstream.' },
    ],
  },
  {
    id: 'review-delivery',
    icon: 'GitPullRequestArrow',
    title: 'Review a delivery',
    tagline: 'Inspect the actual changes, collect evidence, and send a clear decision.',
    steps: [
      {
        id: 'open-review-center',
        title: 'Open the Review Center',
        body: 'Go to Workbench, expand the workspace, and open Review Center above Files. It is a local view and does not add a node to Canvas.',
        action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-review-center:{workspace}' },
      },
      {
        id: 'inspect-diff',
        title: 'Inspect the real changes',
        body: 'Choose a staged or unstaged file. Monaco compares the indexed and changed versions side by side; use the source list to stage, unstage, or commit without switching applications.',
      },
      {
        id: 'capture-context',
        title: 'Capture delivery context',
        body: 'Start a review, link the task and responsible agent, and record the expected outcome, evidence, tests, risks, and included files. The current Git revision is saved with it.',
      },
      {
        id: 'decide',
        title: 'Comment and decide',
        body: 'Click a diff line to comment, then approve, request changes, or reject. Requested changes are submitted to the responsible agent when online; comments remain visible and are marked outdated if the code changes.',
      },
    ],
  },
  {
    id: 'portal-design-feedback',
    icon: 'ScanSearch',
    title: 'Give visual feedback from a Portal',
    tagline: 'Select the exact interface element and send safe, actionable context.',
    steps: [
      {
        id: 'open-portal',
        title: 'Open the real page',
        body: 'Open a Portal in Canvas or Workbench using the installed desktop app. Load the screen and viewport where you found the visual problem.',
        action: { kind: 'openPage', path: '/canvas' },
      },
      {
        id: 'inspect-element',
        title: 'Select the element',
        body: 'Choose Inspect design in the Portal header. Move over the page to highlight real elements and click the exact button, field, image, heading, or layout area. Press Escape to cancel without changing the page.',
      },
      {
        id: 'review-context',
        title: 'Review before sending',
        body: 'Confirm the cropped screenshot, selector, visible text, relevant styles, page path, and viewport. Add the expected outcome. Raw HTML stays in the sanitized preview; cookies, tokens, storage, headers, and query strings are excluded.',
      },
      {
        id: 'send-feedback',
        title: 'Choose the responsible destination',
        body: 'Create a task for leader triage, a task already assigned to a specialist, or append the feedback and PNG to an existing task. Every option keeps context and decisions traceable on the Kanban board.',
      },
    ],
  },
  {
    id: 'council-perspectives',
    icon: 'Scale',
    title: 'Compare perspectives with Council',
    tagline: 'Give independent agents the same question and keep the final decision human.',
    steps: [
      {
        id: 'open-council',
        title: 'Start from the work',
        body: 'Open Council directly from the Canvas toolbar or at the top of the workspace in Workbench. You can also use Ask perspectives on a task to carry its complete brief or from the leader menu to preselect that leader.',
        action: { kind: 'openCouncil' },
      },
      {
        id: 'configure-council',
        title: 'Bound the comparison',
        body: 'Choose two to five real agents, give each a distinct approach, select advisory or implementation mode and a decision criterion, then set the maximum execution count. Optional leader synthesis uses one execution from that budget.',
      },
      {
        id: 'compare-council',
        title: 'Compare the same contract',
        body: 'Review proposal, verified evidence, risks, tests, disagreements, recommendation, and confidence side by side. Completed perspectives remain usable when another provider fails; the leader suggestion is advice, not an automatic verdict.',
      },
      {
        id: 'decide-council',
        title: 'Record the human decision',
        body: 'Select one perspective, request more consensus, or reject the round and save your rationale. In implementation mode, only a selected committed floor can be landed, after a fresh clean and conflict-free preview. Council never pushes or merges by itself.',
      },
    ],
  },
  {
    id: 'mobile-device-testing',
    icon: 'Smartphone',
    title: 'Test an app on iOS or Android',
    tagline: 'Control, inspect, and capture a mobile flow without leaving the workspace.',
    steps: [
      {
        id: 'open-mobile-device',
        title: 'Add Mobile Device',
        body: 'Add Mobile Device from the Canvas toolbar. It becomes one persistent workspace node; Workbench lists and opens that same node. Choose iOS Simulator on Apple Silicon, or Android on macOS, Windows, and Linux with Android Studio Platform Tools installed.',
        action: { kind: 'createDevice', title: 'Mobile Device' },
        check: { kind: 'nodeExists', nodeType: 'device' },
      },
      {
        id: 'attach-simulator',
        title: 'Attach one device',
        body: 'Choose an iPhone or iPad Simulator, an Android AVD, or an ADB-authorized Android device and select Start. Physical Android hardware asks for explicit confirmation. The screen fits by default; zoom and 1:1 controls remain independent. Click or drag to tap and swipe, while the toolbar provides the platform system buttons, rotation, pinch, restart, and stop.',
      },
      {
        id: 'inspect-mobile-flow',
        title: 'Inspect the flow',
        body: 'Open Device tools to type text, install an iOS build or APK from a workspace path, launch a bundle id or Android package/activity, inspect or change permissions, read bounded logs and accessibility data, and save a screenshot under .orkestrai/devices/screenshots.',
      },
      {
        id: 'delegate-mobile-check',
        title: 'Delegate with evidence',
        body: 'Ask an agent to use orkestrai device or the matching MCP tools. Its taps, swipes, screenshots, logs, and accessibility inspection target this workspace session. Stop the session when finished; Orkestrai also cleans up idle helpers it started.',
      },
    ],
  },
  {
    id: 'workspace-automations',
    icon: 'Workflow',
    title: 'Automate repeatable workspace work',
    tagline: 'Connect a precise trigger to a traceable action without hiding what ran.',
    steps: [
      {
        id: 'open-automations',
        title: 'Open Automations',
        body: 'Open Automations from the Canvas toolbar, Workbench explorer, or Command/Ctrl+K. The same workspace automations and execution history appear in every entry point.',
        action: { kind: 'openPage', path: '/terminal?workspace={workspace}&node=workbench-automations:{workspace}' },
      },
      {
        id: 'choose-recipe',
        title: 'Start from a useful recipe',
        body: 'Open Recipes and choose a development, design, marketing, research, or operations starting point. A recipe fills the form but never runs until you review and save it.',
      },
      {
        id: 'configure-trigger-action',
        title: 'Make the contract explicit',
        body: 'Choose the exact event and action. Task, message, Git, GitHub, webhook, file, usage, schedule, and manual triggers can prompt an agent, create a Kanban task, or notify the desktop.',
      },
      {
        id: 'inspect-history',
        title: 'Follow every execution',
        body: 'Use Execution history to inspect trigger input, target agent and provider, output acknowledgement, duration, attempt, and failure. Failed runs expose a bounded retry instead of disappearing.',
      },
    ],
  },
  {
    id: 'remote-workspace-collaboration',
    icon: 'RadioTower',
    title: 'Share a workspace securely',
    tagline: 'Approve the exact remote capabilities for each trusted device.',
    steps: [
      {
        id: 'open-sharing',
        title: 'Open workspace sharing',
        body: 'Open Share workspace from Canvas or Workbench. This experimental feature is off by default and must be enabled explicitly on the host.',
        action: { kind: 'openSharing' },
      },
      {
        id: 'create-invite',
        title: 'Choose the destination and access',
        body: 'Select Viewer, Collaborator, Operator, or Administrator, then choose Browser/mobile for the Remote PWA or Orkestrai app for another installed desktop. The guest can click the app invite to open Orkestrai automatically or use Workspace → Join remote workspace to paste it manually. Share only the matching link or QR code through a trusted channel.',
      },
      {
        id: 'approve-device',
        title: 'Approve the exact device',
        body: 'Compare the device fingerprint before approving it. You can change its role, revoke it immediately, and inspect every accepted or rejected command in the audit trail.',
      },
      {
        id: 'choose-agent-access',
        title: 'Separate conversation from terminal access',
        body: 'Operators can use the safe agent conversation. Administrators can also start or restore an agent. Enable raw terminal access separately for one trusted Administrator device only when needed; it is off by default, limited to one terminal, rate-limited, encrypted, and audited.',
      },
      {
        id: 'use-remote-voice-terminal',
        title: 'Dictate or open the right terminal',
        body: 'In Remote, use the microphone in the leader conversation, another agent conversation, or the terminal. STT runs locally on the host, audio stays encrypted, and the relay never processes it. The overview preserves the leader history and publishes the reply only after the real end of the turn, combining intermediate messages with the final result. Terminal dictation only inserts text. Open terminal closes the dialog and takes over the screen while fitting font, columns, and rows to a phone, tablet, or desktop.',
      },
      {
        id: 'work-remotely',
        title: 'Use or install Remote',
        body: 'After the guest requests access, the host opens Share workspace → Access, compares the fingerprint, and approves the device. In the browser or installable PWA, the guest follows the sanitized overview and can use only the granted commands. Files, notes, portals, mobile devices, credentials, local paths, and Canvas editing remain unavailable; raw terminal output appears only while its separate permission is enabled.',
      },
      {
        id: 'stop-sharing',
        title: 'Stop the session',
        body: 'Stop sharing when the collaboration ends. Orkestrai closes the relay session, revokes active access, and requires a fresh invite before another device can reconnect.',
      },
    ],
  },
  {
    id: 'custom-app-theme',
    icon: 'Palette',
    title: 'Customize the appearance',
    tagline: 'Choose a ready theme or adjust every visual token in the app.',
    steps: [
      {
        id: 'choose-theme',
        title: 'Choose light or dark',
        body: 'Under Settings → Appearance, compare Orkestrai Dark, Graphite, Midnight, and Orkestrai Light. The light option keeps accessible contrast across nodes, panels, icons, provider marks, and hover states.',
      },
      {
        id: 'edit-tokens',
        title: 'Create your own theme',
        body: 'Duplicate the closest theme and edit semantic tokens for surfaces, text, borders, accent, states, grid, and connections. Use Save to persist it.',
      },
      {
        id: 'share-theme',
        title: 'Take the theme with you',
        body: 'Export the custom theme as JSON and import it into another installation. The file is validated and cannot run arbitrary CSS.',
      },
    ],
  },
  {
    id: 'design-collaboration',
    icon: 'MessagesSquare',
    title: 'Collaborate on a Design document',
    tagline: 'Discuss, propose, and approve visual work without losing authorship or revisions.',
    steps: [
      {
        id: 'open-design-collaboration',
        title: 'Open one shared Design document',
        body: 'Create a native Design document and open it. In the right inspector, choose Collaboration to see people, comments, proposals, and edit conflicts in one place.',
        action: [
          { kind: 'createDesign', title: 'Collaborative Design' },
          { kind: 'openDesign', title: 'Collaborative Design' },
        ],
        check: { kind: 'nodeExists', nodeType: 'design', titleIncludes: 'Collaborative Design' },
      },
      {
        id: 'follow-and-comment',
        title: 'Follow the work and anchor feedback',
        body: 'Live participants expose their page, cursor, and selection. Follow one person when reviewing together, select a layer, and add a comment. Replies, mentions, resolution, and authorship stay versioned with the document.',
      },
      {
        id: 'review-proposal',
        title: 'Review before applying',
        body: 'Create or request a visual proposal. Its preview and structural diff do not change the document until a person explicitly approves it. Approval applies every operation atomically; a conflict blocks the write instead of overwriting another participant.',
      },
      {
        id: 'route-and-share',
        title: 'Choose the right decision path',
        body: 'Send uncertain proposals to Council or create an isolated Floor for parallel implementation. When sharing remotely, approve Design separately as View, Comment, Propose, or Edit and decide. Remote receives sanitized summaries, never the scene graph, assets, files, or local paths.',
      },
    ],
  },
  {
    id: 'design-quality',
    icon: 'ShieldCheck',
    title: 'Audit and protect a Design document',
    tagline: 'Find visual defects, start from complete templates, and recover safely.',
    steps: [
      {
        id: 'open-design-quality',
        title: 'Open the quality inspector',
        body: 'Create a native Design document and open Quality in the right inspector. The audit checks naming, clipping, overlap, contrast, and accessibility without changing the artwork.',
        action: [
          { kind: 'createDesign', title: 'Production Design' },
          { kind: 'openDesign', title: 'Production Design' },
        ],
        check: { kind: 'nodeExists', nodeType: 'design', titleIncludes: 'Production Design' },
      },
      { id: 'inspect-quality-issues', title: 'Jump to the exact layer', body: 'Each issue identifies its severity and rule. Select it to focus the affected layer, then fix its property in the same editor and watch the report update.' },
      { id: 'apply-design-template', title: 'Start with a complete native template', body: 'Choose Product, Marketing, Mobile, or Design system. The template creates editable layers, tokens, and, where relevant, prototype flows or components through normal revisioned operations.' },
      { id: 'recover-design-document', title: 'Understand recovery', body: 'Quality also shows the automatic backup and recent bounded history. Restore requires confirmation and creates a new revision; large documents render incrementally while keeping selections and hierarchy available.' },
    ],
  },
  {
    id: 'visual-annotations',
    icon: 'Shapes',
    title: 'Annotate and reuse a Canvas layout',
    tagline: 'Build a visual explanation once, then duplicate it without rebuilding styles.',
    steps: [
      {
        id: 'create-annotation',
        title: 'Add a visual annotation',
        body: 'I create a styled shape on the Canvas. Double-click its text and use the style control to change shape, colors, typography, border, and arrow points.',
        action: { kind: 'createShape', title: 'Review note', shape: 'rounded' },
        check: { kind: 'nodeExists', nodeType: 'shape', titleIncludes: 'Review note' },
      },
      { id: 'duplicate-annotation', title: 'Duplicate without rebuilding', body: 'Select one or more shapes and press Cmd/Ctrl+D, or use the visible duplicate action. Position, size, label, colors, typography, and arrow geometry are preserved with a small offset.' },
      { id: 'copy-paste-annotation', title: 'Reuse a complete arrangement', body: 'Select the shapes, copy with Cmd/Ctrl+C, and paste with Cmd/Ctrl+V. Multi-selection keeps the relative spacing, and every pasted copy remains independently editable.' },
    ],
  },
  {
    id: 'api-client',
    icon: 'FileCode2',
    title: 'Test an API in the Canvas',
    tagline: 'HTTP, GraphQL, WebSocket, and gRPC beside the team, without app switching.',
    steps: [
      {
        id: 'create-client',
        title: 'Add the API Client',
        body: 'I create a persistent API collection with folders, HTTP, GraphQL, WebSocket and gRPC requests, environments, scripts, tests, responses, and history in the same workspace.',
        action: { kind: 'createApiClient', title: 'Project API' },
        check: { kind: 'nodeExists', nodeType: 'apiClient', titleIncludes: 'Project API' },
      },
      { id: 'import-collection', title: 'Link the project collection', body: 'Import Bruno, OpenCollection YAML, Postman v2.1, Swagger 2.0, OpenAPI 3.x, or a complete Orkestrai backup. Existing repository collections stay linked in watch mode, so Canvas/Workbench and project files remain one source of truth.' },
      { id: 'multi-repository', title: 'Authorize sibling repositories', body: 'When this workspace coordinates repositories beside its working directory, open Edit workspace > Additional repositories. Choose each repository once and give it an alias such as api-tests; agents then use @api-tests/bruno without gaining access to arbitrary parent paths.' },
      { id: 'prepare-request', title: 'Prepare a protocol and credentials', body: 'Choose HTTP, GraphQL, WebSocket, or gRPC. Configure environments, headers, API-key/Bearer/Basic auth, or obtain an OAuth 2.0 token through the assisted browser and PKCE flow. Network settings hold cookies, proxy, CA, client certificate, and TLS verification.' },
      { id: 'automate-and-test', title: 'Automate and test with completion', body: 'Choose Postman, Bruno, or Native. Editors suggest pm.*, bru.*, req/res, and test/expect. Use Scripts for Pre/Post-response and switch Assertions/JavaScript in Tests; the source runtime executes scopes, callbacks, Chai, cookies, flow, visualizers, and iteration data.' },
      { id: 'agent-authoring', title: 'Delegate repository-backed tests', body: 'Connect the API Client to an agent or lead. It can import a project-relative Bruno/Postman collection, edit format-native folders, requests, scripts, tests, and variables, execute the suite, and persist linked changes to the original files without exposing local secrets. Orkestrai-only runner settings remain in the node and native backup.' },
      { id: 'send-request', title: 'Inspect and share the result', body: 'Expand or collapse structured JSON/XML responses, inspect WebSocket and gRPC message transcripts, headers, tests, console, timing, size, and history. Export Bruno, OpenCollection, Postman, OpenAPI 3.1, an environment, or the native collection.' },
    ],
  },
  {
    id: 'windows-wsl-agents',
    icon: 'Laptop',
    title: 'Combine Windows and WSL agents',
    tagline: 'Choose the right environment for each terminal in one team.',
    steps: [
      {
        id: 'choose-runtime',
        title: 'Set the workspace default',
        body: 'On Windows, open New workspace or Edit workspace and choose the environment that most of the team should inherit.',
      },
      {
        id: 'choose-distribution',
        title: 'Adjust only the exceptions',
        body: 'While creating an agent or from the terminal compact menu, open Execution environment and choose Workspace default, native Windows, or WSL. A WIN/WSL badge keeps the override visible.',
      },
      {
        id: 'set-linux-path',
        title: 'Select distribution and path',
        body: 'Choose the installation that contains the CLI and confirm the matching Linux project folder. Ubuntu-22.04, Ubuntu-24.04, and Debian remain independent; saving restarts only that terminal in the selected environment.',
      },
    ],
  },
  {
    id: 'saved-terminal-commands',
    icon: 'ListRestart',
    title: 'Save and reuse terminal commands',
    tagline: 'Per-terminal shortcuts, global commands, and safe shell auto-run.',
    steps: [
      {
        id: 'open-saved-commands',
        title: 'Open saved commands',
        body: 'Open a terminal options menu and expand Saved commands. Local and global commands are listed there for immediate execution; choose Create and manage commands to add or edit them.',
      },
      {
        id: 'save-and-run-command',
        title: 'Save and run manually',
        body: 'Give it a clear name, enter the command, and save. Search matches names and contents; Run submits it to the current terminal. Manual execution works in shells and agents.',
      },
      {
        id: 'configure-safe-resume',
        title: 'Automate shells only',
        body: 'In a pure shell, enable Run on resume. The command runs once when that session is created or restored, without repeating as you switch between Canvas and Workbench. Agents never receive auto-run text. Do not save passwords or tokens in commands.',
      },
    ],
  },
  {
    id: 'workspace-folders',
    icon: 'FolderTree',
    title: 'Organize workspaces into folders',
    tagline: 'Group projects by client, team, or environment in the sidebar.',
    steps: [
      { id: 'open-canvas-sidebar', title: 'Open the sidebar', body: 'Expand the Canvas sidebar (the panel toggle in its header) to see the full workspace list.', action: { kind: 'openPage', path: '/canvas?workspace={workspace}' } },
      { id: 'create-workspace-folder', title: 'Create a folder', body: 'Type a name in New folder at the bottom of the list and confirm. It appears at the root, ready to receive workspaces.' },
      { id: 'file-workspace-into-folder', title: 'File a workspace into it', body: 'Drag any workspace onto the folder header to move it there; drag it onto empty space in the list to send it back to the root.' },
      { id: 'create-workspace-in-folder', title: 'Create a workspace already inside a folder', body: 'Hover a folder\'s header and use the plus icon to open New workspace with that folder pre-selected as the destination, or pick any folder from the Folder field in the dialog itself — no dragging needed afterward.' },
      { id: 'nest-workspace-folders', title: 'Nest and manage folders', body: 'Drag one folder onto another to make it a subfolder, or use the "new subfolder" icon in a folder\'s header to create one already inside it — there\'s no depth limit. Rename with the pencil icon or a double-click, and delete with the trash icon: workspaces and subfolders inside always move up to the root instead of being removed.' },
    ],
  },
  {
    id: 'creative-image-workflow',
    icon: 'Images',
    title: 'Create a character and a complete campaign',
    tagline: 'Validate a real chain: character, brand application, and carousel with reused references.',
    steps: [
      {
        id: 'create-director',
        title: 'Create the Creative Director',
        body: 'I add a single Codex agent to control every stage. Use an authenticated Codex account or plan with ImageGen available; no API key is required.',
        action: { kind: 'createAgent', title: 'XYZ Creative Director', provider: 'codex', position: { x: 40, y: 60 } },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'XYZ Creative Director' },
      },
      {
        id: 'prepare-briefs',
        title: 'Prepare reusable briefs',
        body: 'I create a complete brief for the Atomic Ant and another for the fictional XYZ campaign. You can test immediately and edit any detail in the Notes later.',
        action: [
          { kind: 'createNote', title: 'XYZ Character Brief', position: { x: 40, y: 460 }, content: '# Character\nHeroic, charismatic, agile atomic ant with stylized ant anatomy, modern sportswear, and a recognizable silhouette.\n\n## Art direction\nContemporary anime, clean lines, premium finish, friendly expression, full body, and consistent lighting.\n\n## Palette\nBright red, white, black, and small violet accents.\n\n## Consistency\nPreserve the face, antennae, proportions, outfit, and visual identity across every stage. Do not add extra characters or artificial backgrounds.' },
          { kind: 'createNote', title: 'XYZ Brand Campaign', position: { x: 40, y: 800 }, content: '# XYZ Brand\nA creative technology brand for people and agents working together.\n\n## Palette\nViolet #7C4DFF, cyan #22D3EE, black, and white.\n\n## Carousel\n1. Create with people and agents\n2. One workspace, visible progress\n3. Ship better work\n\n## Rules\n4:5 Instagram format, consistent composition, safe copy areas, and a readable logo without distortion.' },
        ],
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'XYZ Brand Campaign' },
      },
      {
        id: 'prepare-character-stage',
        title: 'Build the character stage',
        body: 'I create and connect the first workflow. It requests three transparent masters and saves the PNG files under generated/images/xyz-character.',
        action: [
          { kind: 'createImageWorkflow', title: '01 — Character Master', position: { x: 620, y: 60 }, prompt: 'Create three polished full-body master images of the Atomic Ant described by the connected brief. Each result must use a distinct pose and preserve exactly the same visual identity.', count: 3, transparentBackground: true, outputDirectory: 'generated/images/xyz-character', filePrefix: 'atomic-ant-master' },
          { kind: 'connect', fromTitle: 'XYZ Character Brief', toTitle: '01 — Character Master' },
          { kind: 'connect', fromTitle: 'XYZ Creative Director', toTitle: '01 — Character Master' },
        ],
        check: { kind: 'edgeExists', fromTitle: 'XYZ Creative Director', toTitle: '01 — Character Master' },
      },
      {
        id: 'generate-character',
        title: 'Generate and validate the character',
        body: 'Do it for me dispatches the workflow to the Creative Director. This step advances only after all three files exist in the workspace and three Image nodes have been created on the Canvas.',
        action: { kind: 'runImageWorkflow', title: '01 — Character Master' },
        check: { kind: 'imageWorkflowSucceeded', title: '01 — Character Master', minOutputs: 3 },
      },
      {
        id: 'prepare-brand-stage',
        title: 'Apply a brand to the character',
        body: 'I generate a sample XYZ logo PNG, create the second stage, and automatically connect the first approved master, the logo, both briefs, and the same Codex.',
        action: [
          { kind: 'createSampleImage', title: 'XYZ Sample Logo', path: '.orkestrai/tours/xyz-sample-logo.png', label: 'XYZ', background: '#7C4DFF', foreground: '#FFFFFF', position: { x: 1140, y: 920 } },
          { kind: 'createImageWorkflow', title: '02 — Branded Character', position: { x: 1600, y: 60 }, prompt: 'Use the first reference as the character exact identity and the second as the exact XYZ brand logo. Create two full-body promotional poses with the logo applied naturally and legibly to the outfit. Preserve the face, antennae, anatomy, outfit, palette, and style.', count: 2, transparentBackground: true, outputDirectory: 'generated/images/xyz-branded', filePrefix: 'atomic-ant-xyz' },
          { kind: 'connect', fromTitle: 'XYZ Creative Director', toTitle: '02 — Branded Character' },
          { kind: 'connect', fromTitle: 'XYZ Character Brief', toTitle: '02 — Branded Character' },
          { kind: 'connect', fromTitle: 'XYZ Brand Campaign', toTitle: '02 — Branded Character' },
          { kind: 'connectWorkflowOutput', fromWorkflowTitle: '01 — Character Master', outputIndex: 0, toWorkflowTitle: '02 — Branded Character' },
          { kind: 'connect', fromTitle: 'XYZ Sample Logo', toTitle: '02 — Branded Character' },
        ],
      },
      {
        id: 'generate-branded-character',
        title: 'Generate the branded character',
        body: 'The execution uses both references in the order shown by the workflow. The tour waits for both real results before unlocking the carousel stage.',
        action: { kind: 'runImageWorkflow', title: '02 — Branded Character' },
        check: { kind: 'imageWorkflowSucceeded', title: '02 — Branded Character', minOutputs: 2 },
      },
      {
        id: 'prepare-carousel-stage',
        title: 'Build the carousel from the result',
        body: 'I create the third stage and automatically reuse the first branded character together with the campaign brief. The example uses three slides for a fast validation; the selector supports increasing it to ten.',
        action: [
          { kind: 'createImageWorkflow', title: '03 — XYZ Carousel', position: { x: 2580, y: 60 }, prompt: 'Create a coherent three-image 4:5 Instagram carousel using the connected branded character as the visual identity. Follow the order and content of the three slides in the XYZ Brand Campaign note. Preserve the character, outfit, logo, palette, lighting, and visual language across every slide. Keep safe areas and a clear composition for mobile reading.', count: 3, transparentBackground: false, outputDirectory: 'generated/images/xyz-carousel', filePrefix: 'xyz-carousel-slide' },
          { kind: 'connect', fromTitle: 'XYZ Creative Director', toTitle: '03 — XYZ Carousel' },
          { kind: 'connect', fromTitle: 'XYZ Brand Campaign', toTitle: '03 — XYZ Carousel' },
          { kind: 'connect', fromTitle: 'XYZ Character Brief', toTitle: '03 — XYZ Carousel' },
          { kind: 'connectWorkflowOutput', fromWorkflowTitle: '02 — Branded Character', outputIndex: 0, toWorkflowTitle: '03 — XYZ Carousel' },
        ],
      },
      {
        id: 'generate-carousel',
        title: 'Generate and inspect the complete delivery',
        body: 'Do it for me runs the final stage. The use case finishes only after three slides are persisted and visible on the Canvas. The final graph preserves every prompt, reference, file, connection, run, and source.',
        action: { kind: 'runImageWorkflow', title: '03 — XYZ Carousel' },
        check: { kind: 'imageWorkflowSucceeded', title: '03 — XYZ Carousel', minOutputs: 3 },
      },
    ],
  },
  {
    id: 'code-intelligence-graph',
    icon: 'Waypoints',
    title: 'Understand the code before changing it',
    tagline: 'Index approved repositories and follow real relationships from one bounded visual graph.',
    steps: [
      {
        id: 'create-code-graph',
        title: 'Add the shared graph',
        body: 'I add one Code Graph node to the Canvas. Workbench and every connected agent will use this same persisted index.',
        action: { kind: 'createCodeGraph', title: 'Code Intelligence' },
        check: { kind: 'nodeExists', nodeType: 'codeGraph', titleIncludes: 'Code Intelligence' },
      },
      {
        id: 'index-approved-repositories',
        title: 'Index approved repositories',
        body: 'I scan TypeScript, JavaScript, Svelte, and PHP source from the workspace and any explicitly authorized repository roots. Project code and configuration are never executed.',
        action: { kind: 'indexCodeGraph' },
        check: { kind: 'codeGraphReady' },
      },
      {
        id: 'explore-symbol-impact',
        title: 'Search and follow impact',
        body: 'Search for a service, component, route, or method in the node. Select a result, then switch Incoming, Both, or Outgoing and adjust depth to inspect its bounded neighborhood. Agents can perform the same search with code_graph_search and code_graph_neighbors.',
      },
      {
        id: 'inspect-api-contracts',
        title: 'Trace API contracts across repositories',
        body: 'Open Contracts to connect backend endpoints, frontend calls, generated clients, OpenAPI schemas, gateway prefixes, and live API Client requests. Resolve unmatched calls and cross-project route conflicts before changing either side. Agents use code_graph_contracts for the same bounded map.',
      },
      {
        id: 'inspect-change-impact',
        title: 'Inspect active changes',
        body: 'Open Changes to map the workspace and active Floors onto the same graph. Red symbols changed directly, amber paths identify likely tests, and the side panel exposes overlapping Floor files or downstream symbols. Agents receive the same bounded evidence with code_graph_changes.',
      },
      {
        id: 'handoff-change-impact',
        title: 'Make the evidence actionable',
        body: 'Use the review icon on the workspace scope to create a Review Center item tied to the current Git revision, or the task icon on any workspace or Floor scope to create a Kanban task for the leader. Agents use code_graph_handoff for the same guarded action.',
      },
    ],
  },
  {
    id: 'desktop-diagnostics',
    icon: 'Activity',
    title: 'Diagnose the desktop app',
    tagline: 'Inspect a failed action and collect a bounded local log for support.',
    steps: [
      { id: 'open-developer-tools', title: 'Open Developer tools', body: 'Open View > Developer tools, or press Ctrl+Shift+I on Windows and Linux. Keep Console visible and reproduce the action that did not respond.' },
      { id: 'read-console-error', title: 'Capture the first relevant error', body: 'Copy the first red error and its stack after reproducing the issue. Console remains the fastest view for Usage, Workbench, and other renderer actions that fail without a visible message.' },
      { id: 'open-desktop-logs', title: 'Open the persistent logs', body: 'Choose Help > Open logs folder and send orkestrai.log with the report. Files rotate automatically, common credentials are redacted, and normal agent output is not persisted.' },
    ],
  },
];
