/** Maps every documented use case to the guided tour that exercises it. */
export const USE_CASE_TOUR_IDS: Record<string, string> = {
  'leader-team': 'team-leader',
  'watch-24-7': 'vigia-24-7',
  'parallel-features': 'duas-features',
  'council-decision': 'council-perspectives',
  'api-client-workflow': 'api-client',
  'visual-annotations': 'visual-annotations',
  'creative-image-workflow': 'creative-image-workflow',
  'visual-qa': 'qa-visual',
  'mobile-qa': 'mobile-device-testing',
  'research-summary': 'pesquisa-resumo',
  'inbox-files': 'inbox-arquivos',
  'cross-review': 'revisao-cruzada',
  'choose-agent-provider': 'choose-agent-provider',
  'pin-favorite-agents': 'pin-favorite-agents',
  'setup-agent-provider': 'provider-center-setup',
  'provider-profiles': 'provider-center-setup',
  'deploy-sentinel': 'sentinela-deploy',
  'automate-workspace': 'workspace-automations',
  'framework-preset': 'preset-bootstrap',
  'portable-role-library': 'portable-role-library',
  'custom-workflow': 'custom-board-stages',
  'campaign-launch': 'campaign-ready-team',
  'orkestrai-contributing': 'orkestrai-consensus-team',
  'approval-pipeline': 'pipeline-aprovacao',
  'chained-flows': 'chained-flows',
  'design-figma': 'design-figma',
  'ui-exploration': 'ui-exploration',
  'design-delivery': 'design-delivery',
  'design-prototype': 'design-prototype',
  'design-collaboration': 'design-collaboration',
  'design-quality': 'design-quality',
  'mcp-tools': 'mcp-tools',
  'managed-ports': 'managed-ports',
  'leader-dictation': 'leader-dictation',
  'audio-devices': 'audio-devices',
  'switch-agent-provider': 'switch-agent-provider',
  'devin-local-agent': 'devin-local-agent',
  'multilingual-spoken-replies': 'multilingual-spoken-replies',
  'quota-aware-delegation': 'quota-aware-delegation',
  'organize-canvas': 'organize-canvas',
  'focused-workspace-view': 'focused-workspace-view',
  'monitor-team-control-center': 'monitor-team-control-center',
  'triage-attention-across-workspaces': 'triage-attention-center',
  'trace-delivery-workstream': 'trace-delivery-workstream',
  'preserve-sourced-workspace-memory': 'preserve-sourced-workspace-memory',
  'triage-traceable-annotations': 'triage-traceable-annotations',
  'version-and-share-team-pack': 'version-and-share-team-pack',
  'run-agent-huddle': 'run-agent-huddle',
  'edit-and-preview-files': 'edit-and-preview-files',
  'share-reference-material': 'share-reference-material',
  'universal-workspace-search': 'universal-workspace-search',
  'review-delivery': 'review-delivery',
  'portal-design-feedback': 'portal-design-feedback',
  'remote-collaboration': 'remote-workspace-collaboration',
  'custom-app-theme': 'custom-app-theme',
  'windows-wsl-agents': 'windows-wsl-agents',
  'saved-terminal-commands': 'saved-terminal-commands',
  'code-intelligence-graph': 'code-intelligence-graph',
  'desktop-diagnostics': 'desktop-diagnostics',
};

export function tourIdForUseCase(useCaseId: string): string | null {
  return USE_CASE_TOUR_IDS[useCaseId] ?? null;
}
