import { test, expect } from '@playwright/test';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const headers = { origin: 'http://127.0.0.1:5199' };
test('approves a character and drags its complete version into another workspace', async ({ page, request }) => {
  test.setTimeout(90000);
  page.setDefaultTimeout(10000);
  const pageErrors: string[] = [];
  page.on('pageerror', error => { pageErrors.push(error.message); console.error(error.stack); });
  const folders: string[] = [], workspaceIds: string[] = [];
  const settings = (await (await request.get('/api/agent-room/settings')).json()).data;
  try {
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-light' } });
    for (const name of ['Character origin', 'Character destination']) {
      const folder = await mkdtemp(join(tmpdir(), 'orkestrai-character-e2e-')); folders.push(folder);
      const response = await request.post('/api/agent-room/workspaces', { data: { name, workingDir: folder } });
      expect(response.ok()).toBeTruthy(); workspaceIds.push((await response.json()).data.id);
    }
    const [source, destination] = workspaceIds;
    const png = await readFile(join(process.cwd(), 'electron/resources/icons/512x512.png'));
    const wav = Buffer.alloc(32044); wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(16000, 24); wav.writeUInt32LE(32000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(32000, 40);
    await writeFile(join(folders[0], 'master.png'), png); await writeFile(join(folders[0], 'voice.wav'), wav);
    const endpoint = (id: string) => `/api/agent-room/workspaces/${id}/creative-media/characters`;
    const draft = await request.post(endpoint(source), { headers, data: { command: 'create', definition: { name: 'Mox approved', appearance: 'Geometric red character with green jacket.', images: ['master.png'], voice: { kind: 'audio', path: 'voice.wav', language: 'pt-BR', style: 'Calm' } } } });
    expect(draft.ok()).toBeTruthy();
    const character = (await draft.json()).data;
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.goto(`/canvas?workspace=${source}`);
    await page.getByRole('button', { name: 'Images', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Characters', exact: true }).click();
    expect(pageErrors).toEqual([]);
    const library = page.getByTestId('character-library');
    await library.getByRole('button', { name: 'Manage characters' }).click();
    const dialog = page.getByRole('dialog');
    await expect(dialog.getByRole('textbox').first()).toBeEnabled();
    await dialog.getByRole('combobox', { name: 'Characters', exact: true }).click();
    await page.getByRole('option', { name: /Mox approved/ }).click();
    await expect(dialog.getByRole('textbox').first()).toHaveValue('Mox approved');
    await expect(dialog.locator('audio')).toBeVisible();
    await dialog.locator('audio').evaluate(async (audio: HTMLAudioElement) => { audio.muted = true; await audio.play(); audio.pause(); });
    expect(await dialog.locator('audio').evaluate((audio: HTMLAudioElement) => audio.duration)).toBeCloseTo(1);
    await dialog.getByRole('button', { name: 'Approve and lock', exact: true }).click();
    await page.getByRole('alertdialog').getByRole('button', { name: 'Approve and lock', exact: true }).click();
    await expect(dialog.getByRole('textbox').first()).toBeDisabled();
    await expect(dialog.getByRole('button', { name: 'New version', exact: true })).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await expect(library).toBeVisible();
    await page.goto(`/canvas?workspace=${destination}`);
    if (!await library.isVisible()) {
      await page.getByRole('button', { name: 'Images', exact: true }).click();
      await page.getByRole('menuitem', { name: 'Characters', exact: true }).click();
    }
    const card = library.locator(`[data-character-id="${character.id}"]`);
    await expect(card).toBeVisible();
    await expect(card.locator('img')).toBeVisible();
    const libraryBounds = await library.boundingBox();
    expect(libraryBounds!.width).toBeLessThanOrEqual(340);
    expect(libraryBounds!.x + libraryBounds!.width).toBeLessThanOrEqual(1280);
    const search = library.getByRole('textbox', { name: 'Search characters' });
    const searchBounds = await search.boundingBox();
    expect(await search.evaluate((element, bounds) => element.contains(document.elementFromPoint(bounds.x + bounds.width - 8, bounds.y + bounds.height / 2)), searchBounds!)).toBe(true);
    await page.screenshot({ path: '/tmp/orkestrai-character-library-light.png' });
    const pane = page.locator('.svelte-flow__pane');
    await card.dragTo(pane, { targetPosition: { x: 180, y: 180 } });
    await expect.poll(async () => (await (await request.get(endpoint(destination))).json()).data.length).toBe(1);
    const copy = (await (await request.get(endpoint(destination))).json()).data[0];
    expect(copy).toMatchObject({ state: 'locked', familyId: character.familyId, version: 1 });
    expect(await readFile(join(folders[1], copy.definition.images[0]))).toEqual(png);
    expect(await readFile(join(folders[1], copy.definition.voice.path))).toEqual(wav);
    const nodes = (await (await request.get(`/api/agent-room/workspaces/${destination}/nodes`)).json()).data;
    expect(nodes.map((node: { type: string }) => node.type).sort()).toEqual(['group', 'image', 'note']);
    await library.getByRole('button', { name: 'Close', exact: true }).click();
    await expect(page.locator('.canvas-image img')).toBeVisible();
    await page.screenshot({ path: '/tmp/orkestrai-character-drop-light.png' });
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-dark' } });
    await page.setViewportSize({ width: 1024, height: 640 });
    await page.goto(`/terminal?workspace=${destination}&node=${nodes.find((node: { type: string }) => node.type === 'note').id}`);
    await page.getByRole('button', { name: 'Images', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Characters', exact: true }).click();
    await expect(library.getByText('Mox approved', { exact: true })).toBeVisible();
    await library.getByRole('button', { name: 'Manage characters' }).click();
    await expect(dialog.getByRole('textbox').first()).toBeEnabled();
    await dialog.getByRole('combobox', { name: 'Characters', exact: true }).click();
    await page.getByRole('option', { name: /Mox approved/ }).click();
    await expect(dialog.getByRole('textbox').first()).toBeDisabled();
    const footerButton = dialog.getByRole('button', { name: 'New version', exact: true });
    const bounds = await footerButton.boundingBox(); expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(640);
    await page.screenshot({ path: '/tmp/orkestrai-character-library-dark.png' });
    await footerButton.click();
    await expect(dialog.getByRole('textbox').first()).toBeEnabled();
    const preserved = (await (await request.get(endpoint(destination))).json()).data;
    expect(preserved).toHaveLength(2);
    expect(preserved.find((entry: { id: string }) => entry.id === copy.id)).toEqual(copy);
    let resumeSave!: () => void, saved!: () => void, characterReads = 0;
    const saveGate = new Promise<void>(resolve => resumeSave = resolve);
    const savedOnServer = new Promise<void>(resolve => saved = resolve);
    const delayedSave = `**/workspaces/${destination}/creative-media/characters`;
    await page.route(delayedSave, async route => {
      if (route.request().method() === 'GET') characterReads++;
      if (route.request().method() !== 'POST' || route.request().postDataJSON().command !== 'update') return route.continue();
      const response = await route.fetch();
      saved(); await saveGate; await route.fulfill({ response });
    });
    try {
      await dialog.getByRole('button', { name: 'Save', exact: true }).click();
      await savedOnServer;
      await page.keyboard.press('Escape');
      await expect(dialog).not.toBeVisible();
      await expect(library).toBeVisible();
      await library.getByRole('button', { name: 'Manage characters' }).click();
      await expect.poll(() => characterReads).toBe(1);
      await expect(dialog.getByRole('status')).not.toBeVisible();
      const saveResponse = page.waitForResponse(response => response.request().method() === 'POST' && response.url().includes(`/workspaces/${destination}/creative-media/characters`));
      resumeSave(); await saveResponse;
      await expect(dialog.getByRole('textbox').first()).toBeEnabled();
      expect(characterReads).toBe(1);
      await dialog.getByRole('button', { name: 'New character', exact: true }).click();
      await expect(dialog.getByRole('textbox').first()).toHaveValue('');
    } finally { resumeSave(); await page.unroute(delayedSave); }
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    if (await library.isVisible()) await library.getByRole('button', { name: 'Close', exact: true }).click();
    const modelId = 'bytedance/seedance-2.5/reference-to-video';
    const contract = { id: modelId, name: 'Reference video', status: 'active', category: 'reference-to-video', digest: 'ui-fixture', documentationUrl: 'https://fal.ai/models/bytedance/seedance-2.5/reference-to-video/api', schema: { type: 'object', properties: { prompt: { type: 'string' }, image_urls: { type: 'array', maxItems: 12, items: { type: 'string' } }, audio_urls: { type: 'array', maxItems: 3, items: { type: 'string' } }, generate_audio: { type: 'boolean', default: true } } }, outputSchema: {} };
    await page.route('**/creative-media/models?*', route => route.fulfill({ json: { data: new URL(route.request().url()).searchParams.has('endpoint') ? contract : { models: [contract] } } }));
    const created = await request.post(`/api/agent-room/workspaces/${destination}/creative-media`, { headers, data: { title: 'Character scene', config: { modelId, parameters: { generate_audio: true } } } });
    expect(created.ok()).toBeTruthy();
    const workflow = (await created.json()).data;
    await page.goto(`/terminal?workspace=${destination}&node=${workflow.nodeId}`);
    const video = page.getByTestId('video-workflow');
    await video.getByRole('combobox', { name: 'Bind an approved character' }).click();
    await page.getByRole('option', { name: /Mox approved/ }).click();
    const binding = video.getByTestId('character-binding');
    await expect(binding.locator('img')).toBeVisible();
    await expect(binding.locator('audio')).toBeVisible();
    expect(await binding.locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(512);
    await expect(binding.getByRole('combobox', { name: 'Voice input path' })).not.toBeVisible();
    const prompt = video.getByRole('textbox', { name: 'Direction', exact: true });
    await prompt.fill('Show '); await prompt.pressSequentially('@Mo');
    await expect(video.getByRole('listbox', { name: 'Insert a character reference' })).toBeVisible();
    await prompt.press('Enter');
    await expect(prompt).toHaveValue('Show @{Mox_approved} ');
    await video.getByRole('button', { name: 'Save', exact: true }).click();
    await expect.poll(async () => (await (await request.get(`/api/agent-room/workspaces/${destination}/creative-media/workflows/${workflow.nodeId}`)).json()).data.workflow.config.characterBindings).toEqual([{ id: copy.id, alias: 'Mox_approved', imagePointers: ['/image_urls/0'], voicePointer: '/audio_urls/0' }]);
    await page.reload();
    await expect(prompt).toHaveValue('Show @{Mox_approved}');
    await expect(video.getByText('Provided by the attached references').first()).toBeAttached();
    await page.screenshot({ path: '/tmp/orkestrai-character-scene-dark.png' });
    expect(pageErrors).toEqual([]);
  } finally {
    try {
      await request.put('/api/agent-room/settings', { data: settings }).catch(() => undefined);
      for (const id of workspaceIds) await request.delete(`/api/agent-room/workspaces/${id}`).catch(() => undefined);
    } finally { for (const folder of folders) await rm(folder, { recursive: true, force: true }); }
  }
});
