import { test, expect } from '@playwright/test';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

test('storyboard scenes share Canvas, Workbench and revisioned agent drafts', async ({ page, request }) => {
  test.setTimeout(120000);
  const folder = await mkdtemp(join(tmpdir(), 'orkestrai-storyboard-e2e-'));
  const headers = { origin: 'http://127.0.0.1:5199' };
  const settings = (await (await request.get('/api/agent-room/settings')).json()).data;
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  let workspaceId = '';
  try {
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-light' } });
    workspaceId = (await (await request.post('/api/agent-room/workspaces', { data: { name: 'Storyboard verification', workingDir: folder } })).json()).data.id;
    const base = `/api/agent-room/workspaces/${workspaceId}`;
    await writeFile(join(folder, 'master.png'), await readFile('electron/resources/icons/512x512.png'));
    const image = (await (await request.post(`${base}/nodes`, { data: { type: 'image', title: 'Opening reference', payload: { path: 'master.png' } } })).json()).data;
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.goto(`/terminal?workspace=${workspaceId}`);
    await page.getByRole('button', { name: 'Images', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Storyboard', exact: true }).click();
    const ui = page.getByTestId('storyboard');
    await expect(ui).toBeVisible();
    await ui.getByRole('button', { name: 'Add scene', exact: true }).click();
    await ui.getByRole('textbox', { name: 'Scene title' }).fill('Opening');
    await ui.getByRole('textbox', { name: 'Direction', exact: true }).fill('A bright opening shot, the same approved subject.');
    await ui.getByRole('radio', { name: 'Full body', exact: true }).check();
    await ui.getByRole('textbox', { name: 'Dialogue / narration' }).fill('Welcome to the studio.');
    await ui.getByRole('checkbox', { name: 'Opening reference' }).check();
    await ui.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(ui.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
    await expect(ui.locator('nav img')).toBeVisible();
    await ui.getByRole('button', { name: 'Duplicate scene' }).click();
    await ui.getByRole('textbox', { name: 'Scene title' }).fill('Closing');
    await ui.getByRole('button', { name: 'Save', exact: true }).click();
    await ui.getByRole('button', { name: 'Move scene up' }).click();
    const boards = (await (await request.get(`${base}/creative-media/storyboards`)).json()).data;
    const nodeId = boards[0].nodeId;
    const load = async () => (await (await request.get(`${base}/creative-media/storyboards?nodeId=${nodeId}`)).json()).data;
    await expect.poll(async () => (await load()).storyboard.document.scenes[0].title).toBe('Closing');
    await ui.getByRole('button', { name: 'Prepare image draft' }).click();
    await expect.poll(async () => (await load()).storyboard.document.scenes[0].imageWorkflowNodeId).toBeTruthy();
    await ui.getByRole('button', { name: 'Prepare video draft' }).click();
    await expect.poll(async () => (await load()).storyboard.document.scenes[0].videoWorkflowNodeId).toBeTruthy();
    const board = (await load()).storyboard;
    const scene = board.document.scenes[0];
    expect(scene.shot.framing).toBe('full');
    const workflow = (await (await request.get(`${base}/creative-media/workflows/${scene.videoWorkflowNodeId}`)).json()).data;
    expect(workflow.runs).toEqual([]);
    expect(workflow.workflow.config.shot.framing).toBe('full');
    expect(workflow.workflow.config.requiredReferenceNodeIds).toEqual([image.id]);
    await ui.getByRole('textbox', { name: 'Dialogue / narration' }).fill('Unsaved local dialogue');
    const response = await request.post(`${base}/creative-media/storyboards`, { headers, data: { command: 'apply', nodeId, revision: board.revision, operations: [{ type: 'update', id: scene.id, patch: { title: 'Remote revision' } }] } });
    expect(response.ok()).toBeTruthy();
    await expect(ui.getByText(/This storyboard changed elsewhere/)).toBeVisible({ timeout: 15000 });
    await expect(ui.getByRole('textbox', { name: 'Dialogue / narration' })).toHaveValue('Unsaved local dialogue');
    await ui.getByRole('button', { name: 'Discard edits' }).click();
    await expect(ui.getByRole('textbox', { name: 'Scene title' })).toHaveValue('Remote revision');
    await page.screenshot({ path: '/tmp/orkestrai-storyboard-workbench-light.png' });
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-dark' } });
    await page.setViewportSize({ width: 1024, height: 720 });
    await page.goto(`/canvas?workspace=${workspaceId}`);
    await expect(ui).toBeVisible();
    await expect(ui.locator('nav').getByRole('button', { name: '1. Remote revision' })).toBeVisible();
    await page.screenshot({ path: '/tmp/orkestrai-storyboard-canvas-dark.png' });
    await page.goto(`/terminal?workspace=${workspaceId}&node=${nodeId}`);
    await expect(ui).toBeVisible();
    const bounds = await ui.getByRole('button', { name: 'Discard edits' }).boundingBox();
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(720);
    await ui.getByRole('button', { name: 'Delete', exact: true }).click();
    await page.getByRole('alertdialog').getByRole('button', { name: 'Delete', exact: true }).click();
    await expect.poll(async () => (await load()).storyboard.document.scenes.length).toBe(1);
    expect((await (await request.get(`${base}/nodes`)).json()).data.some((node: { id: string }) => node.id === scene.imageWorkflowNodeId)).toBe(true);
    expect(errors).toEqual([]);
  } finally {
    if (workspaceId) await request.delete(`/api/agent-room/workspaces/${workspaceId}`);
    await request.put('/api/agent-room/settings', { data: settings });
    await rm(folder, { recursive: true, force: true });
  }
});
