import { test, expect } from '@playwright/test';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

test('brand kits are editable, approved and reusable through the native UI', async ({ page, request }) => {
  test.setTimeout(120000);
  const folder = await mkdtemp(join(tmpdir(), 'orkestrai-brand-ui-'));
  const targetFolder = await mkdtemp(join(tmpdir(), 'orkestrai-brand-target-'));
  const settings = (await (await request.get('/api/agent-room/settings')).json()).data;
  const ids: string[] = [], errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  try {
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-light' } });
    const workspace = (await (await request.post('/api/agent-room/workspaces', { data: { name: 'Brand UI acceptance', workingDir: folder } })).json()).data;
    ids.push(workspace.id); const base = `/api/agent-room/workspaces/${workspace.id}`;
    const bytes = await readFile('electron/resources/icons/512x512.png'); await writeFile(join(folder, 'logo.png'), bytes);
    await request.post(`${base}/nodes`, { data: { type: 'image', title: 'Approved mark', payload: { path: 'logo.png' } } });
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.goto(`/terminal?workspace=${workspace.id}`);
    await page.getByRole('button', { name: 'Images', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Brand kits', exact: true }).click();
    const ui = page.getByTestId('brand-library');
    await expect(ui.getByRole('textbox', { name: 'Brand name' })).toBeEnabled();
    await ui.getByRole('textbox', { name: 'Brand name' }).fill('North Studio');
    await ui.getByRole('textbox', { name: 'Communication tone' }).fill('Friendly and precise');
    await ui.getByRole('textbox', { name: 'Usage rules' }).fill('Never distort the mark.');
    await ui.getByRole('button', { name: 'Add color', exact: true }).click();
    await ui.getByRole('textbox', { name: 'Color name 1' }).fill('Primary');
    await ui.getByRole('textbox', { name: 'Hex color 1' }).fill('#2563EB');
    await ui.getByRole('button', { name: 'Attach workspace media', exact: true }).click();
    await ui.getByRole('textbox', { name: 'Asset name 1' }).fill('Mark');
    await ui.getByRole('textbox', { name: 'Workspace-relative file path 1' }).fill('logo.png');
    await ui.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(ui.getByRole('button', { name: 'Approve and lock kit' })).toBeEnabled();
    await ui.getByRole('button', { name: 'Approve and lock kit' }).click();
    await page.getByRole('alertdialog').getByRole('button', { name: 'Approve and lock kit' }).click();
    await expect(ui.getByRole('button', { name: 'Add kit to Canvas' })).toBeEnabled();
    await expect(ui.getByRole('textbox', { name: 'Brand name' })).toBeDisabled();
    const records = (await (await request.get(`${base}/creative-media/brands`)).json()).data;
    expect(records[0].state).toBe('locked');
    await page.screenshot({ path: '/tmp/orkestrai-brand-light.png' });
    await ui.getByRole('button', { name: 'Add kit to Canvas' }).click();
    await expect(ui).not.toBeVisible();
    await expect.poll(async () => (await (await request.get(`${base}/nodes`)).json()).data.filter((node: { type: string }) => node.type === 'note').length).toBe(1);
    const target = (await (await request.post('/api/agent-room/workspaces', { data: { name: 'Brand target acceptance', workingDir: targetFolder } })).json()).data;
    ids.push(target.id);
    await request.put('/api/agent-room/settings', { data: { ...settings, uiLanguage: 'en', appTheme: 'orkestrai-dark' } });
    await page.setViewportSize({ width: 900, height: 650 });
    await page.goto(`/canvas?workspace=${target.id}`);
    await page.getByRole('button', { name: 'Images', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Brand kits', exact: true }).click();
    await ui.getByRole('tab', { name: 'Approved library' }).click();
    await expect(ui.getByRole('tab', { name: 'Approved library' })).toHaveAttribute('aria-selected', 'true');
    await ui.getByRole('textbox', { name: 'Search brand kits' }).fill('North Studio');
    const place = ui.getByRole('button', { name: 'Add kit to Canvas' });
    await expect(place).toBeEnabled();
    const box = await place.boundingBox(); expect(box!.y + box!.height).toBeLessThan(650);
    await page.screenshot({ path: '/tmp/orkestrai-brand-dark.png' });
    await place.click();
    await expect(ui).not.toBeVisible();
    const imported = (await (await request.get(`/api/agent-room/workspaces/${target.id}/creative-media/brands`)).json()).data;
    expect(imported[0].snapshot).toEqual(records[0].snapshot);
    expect((await readFile(join(targetFolder, imported[0].definition.assets[0].path))).equals(bytes)).toBe(true);
    expect(errors).toEqual([]);
  } finally {
    for (const id of ids) await request.delete(`/api/agent-room/workspaces/${id}`);
    await request.put('/api/agent-room/settings', { data: settings });
    await rm(folder, { recursive: true, force: true }); await rm(targetFolder, { recursive: true, force: true });
  }
});
